<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "locations"
//

// locations.placement
$placement = array(
  array("Exhibit"=>"The Chairman Truck","CS_ID"=>30457,"Area"=>"Concessions","New Subarea"=>"Concessions"),
  array("Exhibit"=>"Brittany Crepes","CS_ID"=>30467,"Area"=>"Concessions","New Subarea"=>"Concessions"),
  array("Exhibit"=>"Bacon Bacon","CS_ID"=>33193,"Area"=>"Concessions","New Subarea"=>"Concessions"),
  array("Exhibit"=>"Giant Soap Bubbles","CS_ID"=>19390,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"Crowdsourced Gaming - Balloon Pop!","CS_ID"=>25153,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"Acme Muffineering","CS_ID"=>23658,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"One-Sheet Pedal-Powered Cupcakes","CS_ID"=>26379,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"Motorized La-Z-Boy","CS_ID"=>24250,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"Mission Pony - Urban Horseback Riding","CS_ID"=>21357,"Area"=>"East Side","New Subarea"=>"Center"),
  array("Exhibit"=>"The Red Couch","CS_ID"=>23050,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Steampunk RC Vortex Ring Blaster","CS_ID"=>22234,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Tony Stark and Geppetto collaborate.","CS_ID"=>22862,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Join me: change the world one love note at a time.","CS_ID"=>23617,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Raccoontek Studios Costumes","CS_ID"=>26787,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Creature Quads Hawk and Miss Tickle","CS_ID"=>28061,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Giant Puppet","CS_ID"=>28482,"Area"=>"East Side","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Build and Play Japanese Taiko Drums","CS_ID"=>24625,"Area"=>"East Side","New Subarea"=>"North"),
  array("Exhibit"=>"Holistic Hooping","CS_ID"=>19866,"Area"=>"East Side","New Subarea"=>"North"),
  array("Exhibit"=>"Slaperoo Percussion","CS_ID"=>24750,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Mobile Sound Lab","CS_ID"=>19712,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Tinkers Damn","CS_ID"=>20264,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"CCRMA Musical Interactives","CS_ID"=>26111,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Bubble Top","CS_ID"=>26593,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"KOOBA: The revolutionary targetgame","CS_ID"=>26199,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Trash Amps Portable Speakers","CS_ID"=>22448,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Boxed Kit Amps - Build the Soul Back in Your Sound","CS_ID"=>25737,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Flash Giveaway","CS_ID"=>23379,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Effect of music on human brain waves","CS_ID"=>28126,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"The SND : Sand Noise Device","CS_ID"=>20834,"Area"=>"East Side","New Subarea"=>"South"),
  array("Exhibit"=>"Arduino","CS_ID"=>25876,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Rabbit Proto","CS_ID"=>24819,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Makelangelo Art Robot","CS_ID"=>26384,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Bartendro Cocktail Bots","CS_ID"=>25457,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Makesmith CNC","CS_ID"=>22218,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Hybrid injection / blow molding machine","CS_ID"=>24099,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Mini-Face Metal Casting","CS_ID"=>26606,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Pocket NC","CS_ID"=>23921,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Mold you own plastic parts at home!","CS_ID"=>19610,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Circuit Stickers","CS_ID"=>22462,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Critical Making: Materials, Protocols and Culture","CS_ID"=>25452,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"California College of the Arts // New Projects","CS_ID"=>23066,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Syndicate Design","CS_ID"=>26893,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"The Euclid Robot","CS_ID"=>26734,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Intellectual Property Protection - Is it For Me?","CS_ID"=>29058,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Seeed Studio","CS_ID"=>33177,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Electric Imp","CS_ID"=>32153,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Atmel","CS_ID"=>32135,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"cc Logistics","CS_ID"=>32145,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"TechShop","CS_ID"=>32211,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"MakerBot","CS_ID"=>32173,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Freescale Inc.","CS_ID"=>32157,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Texas Instruments","CS_ID"=>32212,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Epilog Laser","CS_ID"=>32154,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"CNCRouter Parts","CS_ID"=>32143,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Tormach","CS_ID"=>32215,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Full Spectrum Laser","CS_ID"=>32159,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Cooking Hacks by Libelium","CS_ID"=>33147,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Qualcomm","CS_ID"=>32189,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Online Components","CS_ID"=>33168,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Panavise","CS_ID"=>32183,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Sony","CS_ID"=>33183,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"PCH International","CS_ID"=>32184,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Actobotics","CS_ID"=>32127,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Mc Graw Hill","CS_ID"=>33162,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Velleman","CS_ID"=>33189,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"Dropcam","CS_ID"=>32149,"Area"=>"Expo","New Subarea"=>"East"),
  array("Exhibit"=>"DSLR Tethering for Electronic News Gathering (ENG)","CS_ID"=>25208,"Area"=>"Expo","New Subarea"=>"Mobile"),
  array("Exhibit"=>"All of Kinect Robots by SIProp Project","CS_ID"=>27087,"Area"=>"Expo","New Subarea"=>"Mobile"),
  array("Exhibit"=>"ASUS","CS_ID"=>32134,"Area"=>"Expo","New Subarea"=>"North"),
  array("Exhibit"=>"NVIDIA","CS_ID"=>32176,"Area"=>"Expo","New Subarea"=>"North"),
  array("Exhibit"=>"Oracle","CS_ID"=>32181,"Area"=>"Expo","New Subarea"=>"North"),
  array("Exhibit"=>"SparkIO & Pebble","CS_ID"=>32207,"Area"=>"Expo","New Subarea"=>"North"),
  array("Exhibit"=>"Ultimaker","CS_ID"=>32218,"Area"=>"Expo","New Subarea"=>"North"),
  array("Exhibit"=>"I Can Make. Printing the icons of history at home.","CS_ID"=>24779,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Modio","CS_ID"=>23652,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Math Sculptures & Fractal Jewelry","CS_ID"=>22736,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"3D Printed Jewelry and Google Glass Accessories","CS_ID"=>25287,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Bionic Robohand","CS_ID"=>26492,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"e-NABLE 3D-Printed Hands Service Station","CS_ID"=>30521,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Technology For The Sake Of Humanity","CS_ID"=>28349,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Camera Sculptura","CS_ID"=>23573,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"3D Print this Car","CS_ID"=>22948,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Feetz - 3D Printed Custom Fit Shoes","CS_ID"=>24016,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The SandBox 3D Printer","CS_ID"=>27136,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"RoBo 3D: Building Your Future in 3D","CS_ID"=>27376,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"'Overlord' Desktop Delta 3D Printer","CS_ID"=>20390,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"3D Slash","CS_ID"=>28447,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"LIGHTFORGE 3D Printer","CS_ID"=>25058,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Bay Area RepRap: Building 3D Printers For Fun","CS_ID"=>24989,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"TinyG Open Source Motion COntrol for CNC and 3DP","CS_ID"=>23909,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Black Pine Circle School 3D Prints Data & Designs","CS_ID"=>22229,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"City X Project: Creativity & 3D Modeling with Kids","CS_ID"=>20094,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Roy the Robot","CS_ID"=>23615,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"OmNomProject by Genesis3D","CS_ID"=>24631,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"3D printing of humanoid robots","CS_ID"=>22266,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"bhold, Responsive Product Design with 3D Printing","CS_ID"=>25238,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Looking Glass: 3D Printing a Thunderstorm","CS_ID"=>22290,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"3D-Printable Toys by 3DKitbash.com!","CS_ID"=>22877,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Delta Faucet","CS_ID"=>32150,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Type A","CS_ID"=>32216,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Up-Tiertime","CS_ID"=>33186,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Shenzhen Esun Industrial Co.,Ltd","CS_ID"=>32200,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"DWS Systems","CS_ID"=>32151,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Autodesk","CS_ID"=>33141,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Octave/Polymakr","CS_ID"=>32178,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Ideal Jacobs Corp","CS_ID"=>32162,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Fuel 3D","CS_ID"=>33150,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Shapeways","CS_ID"=>32198,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Afinia 3D","CS_ID"=>32129,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Formlabs","CS_ID"=>32156,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"SeeMeCNC","CS_ID"=>33180,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"iMaterialise","CS_ID"=>32164,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Inventables","CS_ID"=>33159,"Area"=>"Expo","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The NeedleArts Zone","CS_ID"=>21603,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"I Weave Straps","CS_ID"=>28103,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Make Your Own Yarn with Spindles & Flyers","CS_ID"=>22699,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Make Your Own Paper Robot!","CS_ID"=>28271,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Make Your Own Soap","CS_ID"=>22445,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Tracimoc, Its Comic Art Backwards!","CS_ID"=>19953,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Patent Depending","CS_ID"=>19632,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"The Journal of Irreproducible Results","CS_ID"=>23207,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Make a Book","CS_ID"=>20458,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Customize Your Own Sketchbook Cover","CS_ID"=>21765,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"A stitch in time","CS_ID"=>20547,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Freeform Common Room","CS_ID"=>24586,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Fiber Fun","CS_ID"=>24575,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Urban Octopus","CS_ID"=>20636,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"geometricks","CS_ID"=>21044,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Corkopolis: A Reuse City on the Move","CS_ID"=>25403,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Glovetopus - Make an octopus from a pair of gloves","CS_ID"=>23671,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Lil DJ: where toddlers become turntablists","CS_ID"=>26622,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"To Green and Beyond","CS_ID"=>20194,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"South Bay Woodworkers Association","CS_ID"=>26490,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Attack of the 10 foot Woolbuddy T-Rex","CS_ID"=>20436,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"The Roost","CS_ID"=>24959,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Rawrz Toys!","CS_ID"=>26477,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Pannaus Props","CS_ID"=>26438,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Modeling Lighting 101","CS_ID"=>26100,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Project Junktopia","CS_ID"=>24076,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Gertie the jumping robot","CS_ID"=>25543,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Scampering Fenn","CS_ID"=>20725,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Guardian Armor Set for Kids","CS_ID"=>21339,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Costumes for Carnival of Venice","CS_ID"=>20298,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Exploring Small Things in a Big Way","CS_ID"=>27031,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Provocraft/Cricut","CS_ID"=>33174,"Area"=>"Expo","New Subarea"=>"Northwest"),
  array("Exhibit"=>"TOBY: Telepresent object beyond yourself","CS_ID"=>20355,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"BRAIGO - A low cost Braille Printer from LEGO","CS_ID"=>20742,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Robot Pi","CS_ID"=>20184,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Solving Rubik's Cubes and Multilingual Prining","CS_ID"=>27105,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"PRAIS - the lord","CS_ID"=>24675,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"EDWARD the Robot","CS_ID"=>22593,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"CuriOdyssey Mobile Museum","CS_ID"=>23022,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Atom II","CS_ID"=>22157,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Rover - A LEGO self-driving car","CS_ID"=>26862,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"An Open Source Autonomous Self Driving DIY Toy Car","CS_ID"=>28429,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Lil 'Bot, the Little Robot that Could","CS_ID"=>21229,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Wearable Dog Gear","CS_ID"=>25216,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Controlling Bluetooth Devices with Raspberry Pi","CS_ID"=>28092,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Chess Playing Robot","CS_ID"=>20620,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"21st Century Robot","CS_ID"=>24176,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Game of Drones - Aerial Action Sports League","CS_ID"=>22537,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Patrick Coyle's Drone","CS_ID"=>28303,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"3D Printed Hexacopter","CS_ID"=>28310,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Junior Drones Team","CS_ID"=>28665,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Stormcenter Research","CS_ID"=>28765,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"BlueQuad","CS_ID"=>29127,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Team Rotor Bits","CS_ID"=>29224,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Rotorbits Team 2","CS_ID"=>29269,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Flying Sloths","CS_ID"=>29451,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"MultiwiiCopter.com - Pro Aerial Video and Photos","CS_ID"=>29476,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"East Peak Drone Team","CS_ID"=>29560,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Nerdrone","CS_ID"=>29603,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Peiqing Xia's Drone","CS_ID"=>29882,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Get to ze choppar","CS_ID"=>29907,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Drones, big and small.","CS_ID"=>29937,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"PreNav","CS_ID"=>30021,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Fpv quadcopter flying at Game of Drones","CS_ID"=>30408,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Lazer Kittens Aerial Drone Team","CS_ID"=>30738,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Faine Greenwood's Drone","CS_ID"=>30811,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Team Rotorbits","CS_ID"=>30858,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"tcopter","CS_ID"=>31402,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Milo's Drone","CS_ID"=>31555,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Skunk Hunter","CS_ID"=>32060,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Team Aerial Systems","CS_ID"=>32336,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Rumble Drones","CS_ID"=>32474,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Team Scarab","CS_ID"=>32498,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Game of Drones","CS_ID"=>32654,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Game of Drones","CS_ID"=>32871,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Orbotix","CS_ID"=>32206,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Microsoft","CS_ID"=>32208,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"ARM","CS_ID"=>32133,"Area"=>"Expo","New Subarea"=>"South"),
  array("Exhibit"=>"Raspberry Pi","CS_ID"=>24680,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"MaKey MaKey","CS_ID"=>29502,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Fabule: Expressive Devices for Creative Homes","CS_ID"=>28739,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"BotFactory Inc.","CS_ID"=>24746,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Tempo Automation","CS_ID"=>22508,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"RPLIDAR/SLAM: Low Cost 360-degree Laser Scanner","CS_ID"=>19351,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"UCSC OpenLab: Art/Science/Tech/Education","CS_ID"=>22458,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"adaptive [tensegrity]","CS_ID"=>23253,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Four Cable Sand Plotter","CS_ID"=>23339,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Argus 3D Scanner","CS_ID"=>24916,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Ferrofluid Art and Design","CS_ID"=>21280,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Steampunk Rock Golem","CS_ID"=>21335,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Authentic armour for cats, rats and mice","CS_ID"=>21500,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Relay Calculating Engine","CS_ID"=>20402,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Not Your Grandpa's Ham Radio 2014","CS_ID"=>27739,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"UC Davis Student Projects","CS_ID"=>20930,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Portable Sensor Attachment","CS_ID"=>19719,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Arduino Water Neutralizer","CS_ID"=>19869,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"ManyLabs: Sensors for Science Education","CS_ID"=>23503,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Arduino-Android Flex Sensor Glove","CS_ID"=>24982,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Mugbot","CS_ID"=>24629,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Resistance!","CS_ID"=>25443,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Rock Vibe: Accessible Gaming","CS_ID"=>24594,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Sensory Perception Chairs","CS_ID"=>19517,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Arduino for home and office","CS_ID"=>27153,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"tapMatrix Touchscreen LED Clock","CS_ID"=>23826,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Taking your Arduino project to the next level","CS_ID"=>20818,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Advanced Audio Library for Arduino Sketches","CS_ID"=>24838,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Mojo - Digital Design for the Hobbyists","CS_ID"=>22337,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Low Voltage Labs","CS_ID"=>23928,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Sense of Things","CS_ID"=>21315,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Bay-Net - 21st Century Amateur Radio","CS_ID"=>22247,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Space Probe Coffee Table","CS_ID"=>21296,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Pisces Project","CS_ID"=>25023,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Invented Art - Kinetics","CS_ID"=>21168,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Invented Art-Laminar Flow","CS_ID"=>21174,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Tapigami","CS_ID"=>26795,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Isopmorphic midi controller keyboard","CS_ID"=>21947,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"GlueMotor - Plug & Play Servo Motor for Smartphone","CS_ID"=>25345,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Pinoccio","CS_ID"=>22964,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"LameStation - DIY Gaming Handheld","CS_ID"=>24627,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"LED Shutter Timer","CS_ID"=>25614,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"SmartMatrix: Large and Colorful LED Displays","CS_ID"=>25034,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"GetLoFi Electronic Audio Kits and Devices","CS_ID"=>19754,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Qfusion Labs: Intuitive electronic building blocks","CS_ID"=>22721,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Freematics","CS_ID"=>20340,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Nano-Quad","CS_ID"=>23154,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Digital View Camera","CS_ID"=>24657,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Applied Kinetic Arts","CS_ID"=>26842,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Armed and Dangerous","CS_ID"=>30401,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Colleen Paz","CS_ID"=>30426,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Twentyseven Gears","CS_ID"=>30623,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Saleae","CS_ID"=>32194,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Microchip Technology","CS_ID"=>33165,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Altera","CS_ID"=>32132,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Nuts & Volts","CS_ID"=>32177,"Area"=>"Expo","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Cupertinker Space","CS_ID"=>25065,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"World Record Paper Airplane","CS_ID"=>19804,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Chemistry Gibberish","CS_ID"=>24344,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"GalaxyGoo Cell Project and More","CS_ID"=>23070,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Telescope Makers' Workshop","CS_ID"=>20214,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Biomonstaaar","CS_ID"=>27095,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Shinamonolab makers collection from Japan","CS_ID"=>25662,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Benicia Makerspace","CS_ID"=>22464,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Santa Barbara Hackerspace","CS_ID"=>25301,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Hacker Lab - Beer Battle + Geography R-R","CS_ID"=>22205,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Bridgewire Makerspace Reno Nv","CS_ID"=>24217,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Talk to electronics with Dangerous Prototypes","CS_ID"=>22325,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"RockIT CoLabs","CS_ID"=>26633,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Hexlab Makerspace, new to Los Angeles (Tarzana)","CS_ID"=>28472,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Ace Monster Toys: Oakland's Foremost Hackerspace","CS_ID"=>22530,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Robot Brigade","CS_ID"=>25079,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Hacker Dojo","CS_ID"=>21310,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"CRASH SPACE","CS_ID"=>22485,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Noisebridge Hackerspace","CS_ID"=>30871,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Hayhackers... Makerspace forming in Hayward, CA","CS_ID"=>24088,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Metrix Open Hardware Alliance","CS_ID"=>23941,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Logos Electromechanical LLC","CS_ID"=>25158,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Nerds For Nature","CS_ID"=>23490,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Counter Culture Labs","CS_ID"=>25598,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Ready, Set, Cereal!","CS_ID"=>25027,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Western Pyrotechnic Assn: Learn to hack fireworks","CS_ID"=>23843,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Ruby Laser","CS_ID"=>24286,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"1000 Maker Stories - Interactive Video Booth","CS_ID"=>25186,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Learningtech.org Workshops","CS_ID"=>20952,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"TakeItApart.com","CS_ID"=>24310,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Robotics, Circuits, & 3- D Printed Kid Inventions","CS_ID"=>26746,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Roboto Picasso","CS_ID"=>19995,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Mousetrap Car Workshop","CS_ID"=>25148,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Fly Your Freak Flag High","CS_ID"=>21673,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Pen Pop-polis","CS_ID"=>23662,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Quick Coasters","CS_ID"=>25601,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"The Great Jungle Race","CS_ID"=>20699,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Wheely: A two-wheel robot for middle school demos","CS_ID"=>19691,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Target shooting Arcade using Infra Red LEDs","CS_ID"=>24180,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Consciousness Hacking","CS_ID"=>22030,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Electronic Frontier Foundation","CS_ID"=>23863,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Wikimedia Foundation","CS_ID"=>20870,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Personal Cosmos - Digital Globe with Projector","CS_ID"=>23231,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"NASA","CS_ID"=>32175,"Area"=>"Expo","New Subarea"=>"Southwest"),
  array("Exhibit"=>"IoT kit","CS_ID"=>27024,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Bay Area LEGO Users Group","CS_ID"=>25341,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"The New Lil' Ju Ju Camp","CS_ID"=>23752,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Perpetual Pinball Machine Trilogy","CS_ID"=>23852,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Shawn Thorsson's Props and Costumes","CS_ID"=>20280,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"COMBAT GARDEN GNOMES","CS_ID"=>20801,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Soundwave: Raspberry PI for Your Costuming","CS_ID"=>25025,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"iPhone Controlled Entertainment Center","CS_ID"=>22982,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Infrared Thermography and Paper Clip Mechanisms","CS_ID"=>25134,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"The New Music Box","CS_ID"=>23324,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Robots That Suck","CS_ID"=>23565,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"CellScope - Cellphone Microscopes for Education","CS_ID"=>25248,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Whimsical Devices","CS_ID"=>24975,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Siege Toys: Desktop-sized siege engine kits","CS_ID"=>24774,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Skallops: BUILD BIG with playing cards!","CS_ID"=>24792,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Bandit Guns ''The most awesomest rubber band gun!''","CS_ID"=>19466,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"TedClocks","CS_ID"=>20377,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Can Cells Learn?","CS_ID"=>19543,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Peppytides: a 3D-printed, foldable molecular model","CS_ID"=>25517,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Quantum Levitation & Superconductivity","CS_ID"=>21187,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Got Robots?","CS_ID"=>24384,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"HomeBrew Robotics Club","CS_ID"=>22682,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Team K.I.S.S Robotics","CS_ID"=>20309,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Twittertyper, Robots, and More","CS_ID"=>23383,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"RobotGrrl's Robots","CS_ID"=>19983,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Interactive robot fight from Bot Bash Party","CS_ID"=>24012,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"PlotterBot - How to build a drawing robot","CS_ID"=>24342,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"PicassoBot","CS_ID"=>25250,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"PancakeBot, *Batter Not Included","CS_ID"=>20338,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Blue Orange Games","CS_ID"=>32139,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"littlebits","CS_ID"=>32170,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Meccano","CS_ID"=>32209,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Vex Robotics","CS_ID"=>32221,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"ROBLOX","CS_ID"=>32192,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"Unity Technologies","CS_ID"=>32219,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"3D Robotics","CS_ID"=>33132,"Area"=>"Expo","New Subarea"=>"West"),
  array("Exhibit"=>"ScrrrAtlas","CS_ID"=>24386,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"Spartan Tethered Europa Explorer (STEEL)","CS_ID"=>24422,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"Maker Educational Pathways research project","CS_ID"=>25388,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"iNet2DVR:Home Automation Made Easy.","CS_ID"=>25494,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"Autonomous Android Vehicle","CS_ID"=>28874,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"Endograft Project: 3D printing architecture","CS_ID"=>29917,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"Challelled Alien Mechanicals","CS_ID"=>30450,"Area"=>"Expo","New Subarea"=>""),
  array("Exhibit"=>"WRRF Presents High School Student Designed Robots","CS_ID"=>21514,"Area"=>"Fiesta","New Subarea"=>"3D Village"),
  array("Exhibit"=>"Aragon Robotics Team presents, ''ART Deco is Back!''","CS_ID"=>26350,"Area"=>"Fiesta","New Subarea"=>"3D Village"),
  array("Exhibit"=>"FIRST Tech Challenge - High School Robotics","CS_ID"=>25477,"Area"=>"Fiesta","New Subarea"=>"3D Village"),
  array("Exhibit"=>"FIRST LEGO League - Middle School Robotics","CS_ID"=>25526,"Area"=>"Fiesta","New Subarea"=>"3D Village"),
  array("Exhibit"=>"ArcAttack!","CS_ID"=>29649,"Area"=>"Fiesta","New Subarea"=>"ArcAttack!"),
  array("Exhibit"=>"LItewall and Interactive Projects,","CS_ID"=>23555,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Light Cloud","CS_ID"=>27282,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Master Control Station and Server Monolith","CS_ID"=>20948,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Tangle and/or Light Curtain","CS_ID"=>28797,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Laser Craze","CS_ID"=>22999,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Metaface as gaia","CS_ID"=>21130,"Area"=>"Fiesta","New Subarea"=>"Center"),
  array("Exhibit"=>"Open source wearables","CS_ID"=>27468,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"Wearables and LEDs from Ireland","CS_ID"=>25075,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"Technically Beautiful","CS_ID"=>22714,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"StepMania: A DIY Dance Dance Revolution","CS_ID"=>20380,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"Predicta PC - The Up-storation of an Iconic Design","CS_ID"=>24038,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"WhaleTail, DuHarley","CS_ID"=>21527,"Area"=>"Fiesta","New Subarea"=>"Foyer East"),
  array("Exhibit"=>"Five Foot Radio Controlled Submarine","CS_ID"=>19859,"Area"=>"Fiesta","New Subarea"=>"Foyer West"),
  array("Exhibit"=>"Virtual Bike","CS_ID"=>26348,"Area"=>"Fiesta","New Subarea"=>"Foyer West"),
  array("Exhibit"=>"R2-D2 Astromech Droids - Bay Area R2 Builders","CS_ID"=>23060,"Area"=>"Fiesta","New Subarea"=>"Foyer West"),
  array("Exhibit"=>"CalHaunts NorCal","CS_ID"=>19562,"Area"=>"Fiesta","New Subarea"=>"Halloween"),
  array("Exhibit"=>"PumpkinFX","CS_ID"=>25263,"Area"=>"Fiesta","New Subarea"=>"Halloween"),
  array("Exhibit"=>"Light-Up Fashion","CS_ID"=>24512,"Area"=>"Fiesta","New Subarea"=>"Mobile"),
  array("Exhibit"=>"The PIXELDELIC Vest.","CS_ID"=>25470,"Area"=>"Fiesta","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Illuminated Wearable Art","CS_ID"=>25538,"Area"=>"Fiesta","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Multimedia Orchestra at Berkeley","CS_ID"=>25489,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Dancing water fountain","CS_ID"=>25051,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Dodecado: Light up your space one block at a time","CS_ID"=>23371,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"tappr.tv","CS_ID"=>24569,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Draw with light and your computer.","CS_ID"=>23777,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Lift","CS_ID"=>21349,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Kovacich Overengineering - Custom Lighting Expo","CS_ID"=>22406,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"LED Art","CS_ID"=>21790,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The Tapestry Electroscope","CS_ID"=>25062,"Area"=>"Fiesta","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Jack SparX - Electricity YOU can SEE and FEEL","CS_ID"=>24848,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Singing Laserium","CS_ID"=>21158,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Sound Wave Dancers","CS_ID"=>24596,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Robot Army","CS_ID"=>20647,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"AerScreen","CS_ID"=>22368,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Center Flee + c4ss4ndr4","CS_ID"=>24896,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"TARDIS Tesla","CS_ID"=>20669,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Total Control LEDs, Arduino, and Cool Neon EL Wire","CS_ID"=>20003,"Area"=>"Fiesta","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Visual Orchestra","CS_ID"=>24833,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Project Gauntl33t","CS_ID"=>24441,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Kindle Fire VR","CS_ID"=>25096,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Xulu Virtual World and Creator Kit","CS_ID"=>24483,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Photographic Phantograms","CS_ID"=>22379,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"3D Photo Booth","CS_ID"=>22381,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Poppy 3D - turn your iPhone into a 3D camera","CS_ID"=>30124,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"3-DIY: Do-It-Yourself Stereoscopic 3-D","CS_ID"=>23481,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"Stereocopic 3-D Projects","CS_ID"=>25021,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"3-D Photography, do it yourself","CS_ID"=>23346,"Area"=>"Fiesta","New Subarea"=>"Robotics"),
  array("Exhibit"=>"The Last Gun","CS_ID"=>22931,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Astro Botanical Glow Forest","CS_ID"=>25831,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Laser Shooting Gallery!","CS_ID"=>22634,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Curious Customs - Artists and Robots!","CS_ID"=>26756,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"OMG Jellyfish by Billion Jelly Bloom","CS_ID"=>21639,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Jellykeepers","CS_ID"=>26812,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Flowtoys Oyeahtoys Flow Zone","CS_ID"=>22555,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"LED Light Sculptures by Kristen Hoard","CS_ID"=>22596,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Electric Giraffe","CS_ID"=>27171,"Area"=>"Fiesta","New Subarea"=>"Southeast"),
  array("Exhibit"=>"DIY animatronic animation using rc servos","CS_ID"=>19321,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Tube Time","CS_ID"=>22898,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Mobile 3D Scanner","CS_ID"=>26987,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"castAR","CS_ID"=>27301,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Virtual Reality with Silicon Valley VR Meetup","CS_ID"=>25429,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Prism gyroscope","CS_ID"=>21179,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Interactive Light Art with Bicycles","CS_ID"=>23898,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"PersonaLED","CS_ID"=>26404,"Area"=>"Fiesta","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Rockenbok","CS_ID"=>32193,"Area"=>"Maker Shed","New Subarea"=>"Outside South"),
  array("Exhibit"=>"candelaphytes","CS_ID"=>27749,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"LEGOJeep","CS_ID"=>25869,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"Young Maker Photo Booth","CS_ID"=>25564,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"Tower of Tetrahedrons","CS_ID"=>24957,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"VCJH Fly Tours","CS_ID"=>19678,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"Paraplane","CS_ID"=>19836,"Area"=>"Midway","New Subarea"=>"Center"),
  array("Exhibit"=>"BVHM Duct Tape Creations","CS_ID"=>25169,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"Maker Camp 2014","CS_ID"=>25891,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"Learn to Solder","CS_ID"=>29636,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"Cognizant","CS_ID"=>32147,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"RadioShack","CS_ID"=>32190,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"Intel","CS_ID"=>32166,"Area"=>"Midway","New Subarea"=>"South"),
  array("Exhibit"=>"Talon Action Camera Mounting Systems by Aquaminor","CS_ID"=>23180,"Area"=>"North Courtyard","New Subarea"=>"Center"),
  array("Exhibit"=>"Masterworks Wood Bicycles","CS_ID"=>20950,"Area"=>"North Courtyard","New Subarea"=>"Center"),
  array("Exhibit"=>"Camp Pedal Power","CS_ID"=>27511,"Area"=>"North Courtyard","New Subarea"=>"Center"),
  array("Exhibit"=>"Archimedes Design","CS_ID"=>23533,"Area"=>"North Courtyard","New Subarea"=>"Center"),
  array("Exhibit"=>"BitLock: Keyless bike lock to enable bikesharing","CS_ID"=>25562,"Area"=>"North Courtyard","New Subarea"=>"Center"),
  array("Exhibit"=>"The Edomites","CS_ID"=>20009,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Cosmic Venus","CS_ID"=>20772,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Illusionist Bryan Patrick","CS_ID"=>21074,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Broken Cities","CS_ID"=>22356,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Dacassi (Electronic Dance Music)","CS_ID"=>26004,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Justin Ancheta Band","CS_ID"=>27541,"Area"=>"North Courtyard","New Subarea"=>"Pedal Powered Stage"),
  array("Exhibit"=>"Hacker vs. Hacker","CS_ID"=>25252,"Area"=>"North Courtyard","New Subarea"=>"South"),
  array("Exhibit"=>"Balsa Wood Gliders","CS_ID"=>26042,"Area"=>"North Courtyard","New Subarea"=>"South"),
  array("Exhibit"=>"Strawbees! Dream big, build bigger!","CS_ID"=>24663,"Area"=>"North Courtyard","New Subarea"=>"South"),
  array("Exhibit"=>"Lawrence Hall of Science - Design, Build, and Test","CS_ID"=>26907,"Area"=>"North Courtyard","New Subarea"=>"South"),
  array("Exhibit"=>"The Zen Gardener","CS_ID"=>20081,"Area"=>"North Courtyard","New Subarea"=>"South"),
  array("Exhibit"=>"Laser tag with 1/16 scale model tanks","CS_ID"=>26121,"Area"=>"North Courtyard","New Subarea"=>"Southeast"),
  array("Exhibit"=>"MakerKids","CS_ID"=>23524,"Area"=>"North Courtyard","New Subarea"=>"Southwest"),
  array("Exhibit"=>"(rc) LabRats S.A.L.T.E.D. amphibious rescue vehicl","CS_ID"=>21123,"Area"=>"North Courtyard","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Maker Shed","CS_ID"=>30376,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"TinyCircuits - Make of Tiny Open Source Circuits","CS_ID"=>23132,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"SpinBots! An ArtBots workshop for kids","CS_ID"=>25399,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"SpikenzieLabs Kits","CS_ID"=>26391,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"Little Robot Friends","CS_ID"=>28677,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"ROBOTIS: DARWIN MINI Dancing Team","CS_ID"=>30352,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"Angular Clock","CS_ID"=>31613,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"blink(1) USB RGB LEDs and BlinkM Smart LEDs","CS_ID"=>31834,"Area"=>"Redwood","New Subarea"=>"Maker Shed"),
  array("Exhibit"=>"Lockpick Village - Presented by TOOOL","CS_ID"=>23814,"Area"=>"Redwood","New Subarea"=>"Outside North"),
  array("Exhibit"=>"Posables Interactive Sculpture Garden","CS_ID"=>19919,"Area"=>"Redwood","New Subarea"=>"Outside Northwest"),
  array("Exhibit"=>"Young Makers","CS_ID"=>23631,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Invent-a-tent","CS_ID"=>33065,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Flipchat","CS_ID"=>33067,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Battery-Powered Air Conditioner","CS_ID"=>33068,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Home Automation using Arduino","CS_ID"=>33069,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"ATRRV","CS_ID"=>33070,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Hamburger Robot","CS_ID"=>33071,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Haunted House","CS_ID"=>33072,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Adjustable Hot Wheels Race Car Tracks","CS_ID"=>33073,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Harmonograph","CS_ID"=>33074,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"catapult","CS_ID"=>33075,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Boffer Sword Play","CS_ID"=>33076,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Dancing With the LEDs","CS_ID"=>33077,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Flashy Skirt - A Dancers Dream","CS_ID"=>33078,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Blue Suede Shoes","CS_ID"=>33079,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Chocolate Drawings","CS_ID"=>33080,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Cupcake Oven","CS_ID"=>33081,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"42 Different things to make","CS_ID"=>33082,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Building Blocks","CS_ID"=>33083,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Jeopardy Buzzer","CS_ID"=>33084,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Balsa wood airplane","CS_ID"=>33085,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Explosive Car","CS_ID"=>33086,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Flying Monster","CS_ID"=>33087,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Beedo Beedo","CS_ID"=>33088,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Bling Bling","CS_ID"=>33089,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Electro-wind","CS_ID"=>33090,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"360 bike-light","CS_ID"=>33091,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Hovertrain","CS_ID"=>33092,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Arduino controlled train","CS_ID"=>33093,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Buggy Jr.","CS_ID"=>33094,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Bob-About","CS_ID"=>33095,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Laser Sharks and Electric Currents","CS_ID"=>33096,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Band in a Box","CS_ID"=>33097,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"El Wire Dress","CS_ID"=>33098,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Mario-in-the-box","CS_ID"=>33099,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Baseball pins","CS_ID"=>33100,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Light Up Ping Pong Table ","CS_ID"=>33101,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"LED Sign","CS_ID"=>33102,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Kids Help Network","CS_ID"=>33103,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Animal Navigator","CS_ID"=>33104,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Cloud Lamp","CS_ID"=>33105,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"BattleCross ''Safe, Smart & Sweeet'' MultiPlayer Game App Featuring ''Maker Faire Bot''","CS_ID"=>33106,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"The Grid","CS_ID"=>22879,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"St.Paul's School Robots","CS_ID"=>23696,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Mt. Valley Fold","CS_ID"=>25175,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Building Meaning of Math Through Making","CS_ID"=>20978,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Kids to Kickstarter: 3D printing in middle schools","CS_ID"=>19977,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"TechGYRLS of YWCA of Silicon Valley","CS_ID"=>23563,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Bourn Idea Lab @ Castilleja School","CS_ID"=>25317,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Applied Science and Engineering Student Projects","CS_ID"=>21270,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Lighthouse Creativity Lab","CS_ID"=>21302,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Solar Chargers","CS_ID"=>21414,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Light Up","CS_ID"=>21416,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"The Hangout Bench","CS_ID"=>21418,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Project FreeLancer","CS_ID"=>21434,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"NukeCity","CS_ID"=>21437,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Electrical Go-Kart","CS_ID"=>21439,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"UseYourHead","CS_ID"=>21441,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Quadcopter","CS_ID"=>21447,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Driftcycle","CS_ID"=>21459,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"dance with lights","CS_ID"=>22541,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"solar panel car","CS_ID"=>23095,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"catle pult","CS_ID"=>23098,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"harplaze","CS_ID"=>23309,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"FBI Earpieces","CS_ID"=>28215,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Plastic Mold Vacuform","CS_ID"=>28508,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Goo Station","CS_ID"=>28514,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Service and Design Engineering @ The Nueva School","CS_ID"=>21691,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"EEME","CS_ID"=>20659,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Pioneers in Engineering","CS_ID"=>22647,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"Lick-Wilmerding High School Technical Arts Program","CS_ID"=>21664,"Area"=>"Sequoia","New Subarea"=>"Young Makers"),
  array("Exhibit"=>"The Athenian School","CS_ID"=>23820,"Area"=>"Sequoia","New Subarea"=>""),
  array("Exhibit"=>"Ritual Coffee","CS_ID"=>30923,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Mushroom Cultivation and Ecology","CS_ID"=>26086,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Cultivar's RainCloud","CS_ID"=>27536,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"internet of farming arduino-based aquaponics","CS_ID"=>20475,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"OpenSprinkler: An Open-Source Sprinkler Timer","CS_ID"=>27396,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"WORMS, WORMS, WORMS!","CS_ID"=>26520,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Honey + Bees = Happy","CS_ID"=>21519,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"HOMEGROWN.org","CS_ID"=>24725,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"FARMcurious Homesteading & DIY Food Booth","CS_ID"=>19477,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Blue House Farm - Community Supported Agriculture","CS_ID"=>31861,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Grow Your Own Organic Mushrooms","CS_ID"=>27990,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Beekeeper's Guild of San Mateo County","CS_ID"=>20061,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Master Gardeners: Make A Succulent Centerpiece","CS_ID"=>21482,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Compass Green","CS_ID"=>29191,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Sweet Treats to eat","CS_ID"=>29338,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"T-WE TEA - SF handmade teas","CS_ID"=>23890,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Hilo There! Plumeria Flours Hawaiian Sweet Treats","CS_ID"=>29277,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"p.o.p. candy co. fresh butter crunch pleasure!","CS_ID"=>29353,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Suite Foods Waffles","CS_ID"=>22778,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"All things chocolate by Kika's Treats","CS_ID"=>27190,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Maison de Monaco: french inspired fruit preserves","CS_ID"=>27274,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Forage Kitchen","CS_ID"=>28949,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Make Low Cost Solar Panels With a Laminator","CS_ID"=>24258,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Open Source Water Quality Sensors","CS_ID"=>19830,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"The Cluck Bucket: A Solar Egg Incubator","CS_ID"=>27097,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"PhotosynQ: The Global Plant Happiness Project","CS_ID"=>26725,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"A Spice Above Gourmet Dips, Spreads, & Dressings","CS_ID"=>22958,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Charlie Frank's Pies","CS_ID"=>21002,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Happy Girl Kitchen Co.-Food that Feeds your Soul","CS_ID"=>21745,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Smitten Truffles: Where Imagination and Chocolate Meet","CS_ID"=>20610,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Oaktown Jerk: Beef Jerky 101","CS_ID"=>19698,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"McVicker Pickles","CS_ID"=>25089,"Area"=>"Show Barn","New Subarea"=>"Homegrown Village"),
  array("Exhibit"=>"Sharing Shuttle / Cohousing Coach","CS_ID"=>22650,"Area"=>"South Lot","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Smoke ring trike 2.0","CS_ID"=>25111,"Area"=>"South Lot","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Home Built Quad Bicycle","CS_ID"=>26196,"Area"=>"South Lot","New Subarea"=>"Mobile"),
  array("Exhibit"=>"Grandpa's Train...","CS_ID"=>27531,"Area"=>"South Lot","New Subarea"=>"Mobile"),
  array("Exhibit"=>"AHS RE: Useables","CS_ID"=>20788,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Sophie's World","CS_ID"=>19454,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Reuse * Repurpose * Recycle * ReLove","CS_ID"=>23456,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"How to using a Sewing Machine & or a Serger","CS_ID"=>27008,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Just Us Girls' Pat-On-The-Back Medallions","CS_ID"=>25757,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"44 Daughters","CS_ID"=>26613,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Trash to Treasure - Easy, Fun DIY Jewelry Kits","CS_ID"=>24784,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Ele Story","CS_ID"=>22934,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Poketti Plushies with a Pocket","CS_ID"=>27866,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Creative Reuse with SCRAP","CS_ID"=>21363,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"CULTIVO SUSTAINABLE DESIGN","CS_ID"=>20529,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Upcycled Paper Crafts","CS_ID"=>24158,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Sanger Community Science Workshop","CS_ID"=>24332,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Amos Goldbaum","CS_ID"=>30139,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Animal Instincts","CS_ID"=>30141,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Art of Natalie McKean","CS_ID"=>30143,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Blushie","CS_ID"=>30148,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Bug Under Glass","CS_ID"=>30150,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"C Westbrook Designs","CS_ID"=>30152,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Cadette","CS_ID"=>30153,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"City Green","CS_ID"=>30155,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Compass Rose Design","CS_ID"=>30157,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Delusions of Grandeur","CS_ID"=>30160,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"e.b.friday","CS_ID"=>30162,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"field day","CS_ID"=>30167,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Fluff Engine","CS_ID"=>30169,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"hrvst3D","CS_ID"=>30175,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Isabella Kung","CS_ID"=>30177,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Jumbo Jibbles","CS_ID"=>30178,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Le Petit Elefant","CS_ID"=>30186,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Martin Hsu Art and Design","CS_ID"=>30188,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"MXM Jewelry","CS_ID"=>30190,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"PassionWood Designs","CS_ID"=>30195,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Rhythmic Metal","CS_ID"=>30200,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Robots by Matt Q. Spangler","CS_ID"=>30201,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Steamy Tech","CS_ID"=>30206,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The Enchanted Square","CS_ID"=>30208,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The Girl and Rhino","CS_ID"=>30209,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Unpossible Cuts","CS_ID"=>30215,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Yetis and Friends","CS_ID"=>30220,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Zoa Chimerum Jewelry","CS_ID"=>30222,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"San Francisco Bazaar","CS_ID"=>30778,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"orangeheat","CS_ID"=>32585,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Puppet Bakery","CS_ID"=>32593,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Revivall Clothing","CS_ID"=>32599,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Field Days Warrior","CS_ID"=>20864,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Rolling Collage Factory","CS_ID"=>22591,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Swap-O-Rama-Rama","CS_ID"=>29697,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"DIY T-Shirt Slashing Workshop with Eva Inez Heule","CS_ID"=>31075,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Recycled Jeans to Skirts","CS_ID"=>31287,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Swap-o-rama-rama","CS_ID"=>31756,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Fresh Prints: Live Silk-Screening with Homeygrown","CS_ID"=>32349,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Fab Lab San Diego and the MIT Mobile Fab Lab","CS_ID"=>27141,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Boxouse","CS_ID"=>26328,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Upcycle Your Plastic with ArribaCycle","CS_ID"=>23787,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Shopping Bag Solutions","CS_ID"=>20987,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Crochet Jam","CS_ID"=>28324,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Superway","CS_ID"=>21000,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"SJSU Spatial Art: Fire Arts and GALLERY WARS!","CS_ID"=>24825,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Swap-O-Rama-Rama's TrasHion Show","CS_ID"=>28887,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"SF Media Co.","CS_ID"=>32199,"Area"=>"South Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"DOOP","CS_ID"=>20638,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"PCC Engineering Club","CS_ID"=>25315,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"The House of Cards","CS_ID"=>20331,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Steamboat Ed's Mechanical Whatsits","CS_ID"=>20778,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Kinetic Steam Works - Anti-Hysteria Couches","CS_ID"=>25010,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Whiskeydrome","CS_ID"=>30809,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Toofastforlove","CS_ID"=>20794,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Mock 1","CS_ID"=>22278,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Nimby Power Wheels Racing","CS_ID"=>22439,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Powerwheels Racing - Team Hellamatics","CS_ID"=>22757,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Power Racing Series","CS_ID"=>23056,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"RADLAMP Power Wheels Car","CS_ID"=>23178,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"PowerWheels Racer Team NCC1702","CS_ID"=>26190,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"The Stig Racing Team","CS_ID"=>26271,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Lil Buddy pedal car","CS_ID"=>28506,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Lil Top","CS_ID"=>28652,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Whimsical Bicycle Sculptures","CS_ID"=>28971,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"the Death Defying Figure Eight Pedal Car Races","CS_ID"=>29008,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Robots and Racing","CS_ID"=>29094,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"#3 Pedal Car Racer","CS_ID"=>29472,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"the Two Penny","CS_ID"=>29482,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"8 Pack Pedal Car","CS_ID"=>29713,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Radlamp Race Team","CS_ID"=>29718,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Whymcycles..Cozy Roadster for the Figure 8 Race","CS_ID"=>29823,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"PPPRS Racing Series Dragon Wagon","CS_ID"=>29891,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Racer 5 peddlecar","CS_ID"=>30488,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"pedal car races","CS_ID"=>30509,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Team Kiss My Snake","CS_ID"=>31771,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Daft Junk","CS_ID"=>31778,"Area"=>"South Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"Spinning Mermaid Fibers","CS_ID"=>30133,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>".retool.","CS_ID"=>30134,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"11:11 enterprises","CS_ID"=>30135,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"7 Starr St","CS_ID"=>30136,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"A Needle Runs Through it","CS_ID"=>30137,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Alchemilla","CS_ID"=>30138,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Ana Apple","CS_ID"=>30140,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Applesauce Designs","CS_ID"=>30142,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Artha Handmade Hemp Soap","CS_ID"=>30144,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"As Wood As It Gets","CS_ID"=>30145,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"B+ Shop","CS_ID"=>30146,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Bird of Virtue","CS_ID"=>30147,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Bottle of Clouds","CS_ID"=>30149,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Cody Vrosh & Binary Winter Press","CS_ID"=>30156,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Craftosterone","CS_ID"=>30158,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Dragon's Treasure","CS_ID"=>30161,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Eco Apothecary","CS_ID"=>30163,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Ex-Boyfriend","CS_ID"=>30164,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Feathery Leathery","CS_ID"=>30165,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Fernworks","CS_ID"=>30166,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"fiftyseven-thirtythree","CS_ID"=>30168,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Glitter Side","CS_ID"=>30170,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Hanasaurusrex","CS_ID"=>30171,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"High Prairie Pottery","CS_ID"=>30172,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"HiLo Studio","CS_ID"=>30173,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"House of Honore","CS_ID"=>30174,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Katy Kristin","CS_ID"=>30179,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Korrupt Label","CS_ID"=>30180,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"KrakenWhip","CS_ID"=>30181,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Krista Tranquilla","CS_ID"=>30182,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Lady Alamo","CS_ID"=>30183,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Laughing Devil Designs, LLC","CS_ID"=>30184,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Laurel Begley Ceramics","CS_ID"=>30185,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"MAHOOHOO","CS_ID"=>30187,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Miss Leah Dee Jewelry","CS_ID"=>30189,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Neural Network","CS_ID"=>30191,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"oddfauna","CS_ID"=>30193,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"oh, hello friend","CS_ID"=>30194,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Pockit Lab","CS_ID"=>30196,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Pretty Fun Designs","CS_ID"=>30197,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Rebicyclist","CS_ID"=>30198,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Recover Your Thoughts","CS_ID"=>30199,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"rubygirl","CS_ID"=>30202,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Skeletal Dropkick","CS_ID"=>30203,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Socko Co.","CS_ID"=>30204,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Sweaty Taxidermy","CS_ID"=>30207,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Tina Produce","CS_ID"=>30211,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Tinkertart","CS_ID"=>30212,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"tofufu","CS_ID"=>30213,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"tomat","CS_ID"=>30214,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Vanda Playing Cards","CS_ID"=>30216,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Vaya Bags","CS_ID"=>30217,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Vitamini","CS_ID"=>30218,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Vivi Kids","CS_ID"=>30219,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Yuki Yamagata Illustration","CS_ID"=>30221,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"By Nieves :: Handmade Natural Body Care","CS_ID"=>30354,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Sora Designs","CS_ID"=>30361,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Hummus Apparel","CS_ID"=>30367,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"RossLab","CS_ID"=>30378,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"Chris Yates Studios","CS_ID"=>30531,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"DawnKathrynStudio","CS_ID"=>30537,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"nothing-obvious","CS_ID"=>30543,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"The Gold Bug","CS_ID"=>30549,"Area"=>"South Lot","New Subarea"=>"San Francisco Bazaar"),
  array("Exhibit"=>"The AVAVA Folly One - Build Your Own Space","CS_ID"=>27365,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"High Striker: Test Your Strength","CS_ID"=>24494,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Oscillation II & Motofurniture","CS_ID"=>27561,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Justin Gray's fire sculpture robots in the sand!","CS_ID"=>26591,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Crucible","CS_ID"=>23012,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Jacktrack","CS_ID"=>21116,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Learn How To Make Glass Beads!","CS_ID"=>19821,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Kits by Kids","CS_ID"=>21020,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Scanning Drone","CS_ID"=>19937,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"iQuad Tilt-Rotor Quadcopter","CS_ID"=>26900,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"AeroQuad - The open source multicopter project!","CS_ID"=>23152,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Virtualrobotix","CS_ID"=>28338,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Compressed Air Rockets","CS_ID"=>23964,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Cat of a Differrent Color (CDC)","CS_ID"=>21191,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Chester the Fire Breathing Horse Art Car","CS_ID"=>25004,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"American Steel Studios","CS_ID"=>30960,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"FLUXCycles","CS_ID"=>29864,"Area"=>"South Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Cyclecide","CS_ID"=>29364,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Titanoboa: A 50 ft Electro-mechanical Snake","CS_ID"=>28240,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"All Power Labs Power Pallet","CS_ID"=>20464,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"3D welder","CS_ID"=>26889,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Karmin Projects","CS_ID"=>24094,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"MIcrotch","CS_ID"=>19526,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Onewheel","CS_ID"=>28206,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Chain Loose","CS_ID"=>24252,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"The VESSEL Bike project","CS_ID"=>25417,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Amphibious Tandem Tricycle","CS_ID"=>22164,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Electric Essence Go Kart","CS_ID"=>21635,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Skatehack","CS_ID"=>23186,"Area"=>"South Lot","New Subarea"=>"Southwest"),
  array("Exhibit"=>"Sustainable Homebrewing Workshop","CS_ID"=>25851,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Metal Arts Guild: metal arts workshops and demos","CS_ID"=>23736,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Roominate: The DIY Wired Building Kit","CS_ID"=>24801,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Tynker Makes Programming Fun","CS_ID"=>30900,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"How to Make It at the San Mateo County Library","CS_ID"=>23500,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Mill Valley Makers's Collection of Project","CS_ID"=>22180,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Sentry Gun Robot","CS_ID"=>27789,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Bay Area Garden Railway Live Steamers","CS_ID"=>20396,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Bike Powered Cardboard Elephant","CS_ID"=>25431,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Kinetic Creatures & Tanenbaum Fabrications","CS_ID"=>25487,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Model Train Scenery, Kit Building & Kitbashing.","CS_ID"=>22580,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Framed collage of upcycled textile & mixed media","CS_ID"=>25435,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Grizzly Peak 3D Printed Model Trains","CS_ID"=>21524,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Gemstone Polishing","CS_ID"=>25556,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Autism Social Connection","CS_ID"=>28174,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Start Making! @ Computer Clubhouses","CS_ID"=>26496,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"MakerState Pop Up Kid's MakerSpace","CS_ID"=>24695,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Maker Junior: Onsite Maker Programming for Kids","CS_ID"=>24299,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"California Teacher Pathway","CS_ID"=>26578,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Marshmallow Shooters","CS_ID"=>24437,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Survival Gear","CS_ID"=>26761,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"CitY3K: Pinball of the Future","CS_ID"=>24206,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Curiosity Hacked","CS_ID"=>20858,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Meet Romibo! A Social Robot by Origami Robotics","CS_ID"=>26428,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"MAKEablez: Creative Art Kits Designed by Kids","CS_ID"=>20767,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Make a Jean Purse","CS_ID"=>19763,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"GridBeam","CS_ID"=>24346,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Riveropolis PLAY RIVER with city & boat design","CS_ID"=>26277,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Trackers Earth: Bay Area","CS_ID"=>27553,"Area"=>"The Yard","New Subarea"=>"North"),
  array("Exhibit"=>"Neon Art Shop","CS_ID"=>24239,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Nutty, Dave's Marbling Magic: Fabric, Paper & More","CS_ID"=>22129,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Drill It & Grind It! Soapstone Beadmaking","CS_ID"=>24485,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Leaf and Light (Oakland tree salvage)","CS_ID"=>19331,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"The incredible edible living wall","CS_ID"=>22308,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Ceallach Dyes: Solar Dyeing","CS_ID"=>23119,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Grow Your Own Spirulina Algae Superfood!","CS_ID"=>24146,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Solrmatic - Automatic Solar Cooking","CS_ID"=>25179,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"BootstrapSolar Chi-qoo DIY Solar Power Pack Kit","CS_ID"=>26949,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Open Source Living Room","CS_ID"=>26667,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Create your own Ultimate Camping & Survival Stove!","CS_ID"=>22656,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Timbrr!","CS_ID"=>20030,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"ZomeBuilder","CS_ID"=>21163,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Build Your Dreams with the PLY90","CS_ID"=>24616,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Gypsy wagon","CS_ID"=>24139,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Stilt Factory","CS_ID"=>24174,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"FIREWORKS and FLOWERCLOUDS","CS_ID"=>25231,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"ShopBot Tools","CS_ID"=>32202,"Area"=>"The Yard","New Subarea"=>"South"),
  array("Exhibit"=>"Gilly","CS_ID"=>23704,"Area"=>"West Green","New Subarea"=>"Center E"),
  array("Exhibit"=>"Mobile Ham Radio Stations","CS_ID"=>23007,"Area"=>"West Green","New Subarea"=>"Expo West"),
  array("Exhibit"=>"Tables and Paddles","CS_ID"=>25905,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"NorCal Mars Rover Project","CS_ID"=>25437,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"Marin Maker Mobile","CS_ID"=>24878,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"FrisbeeCam","CS_ID"=>24644,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"Make geometric art with ITSPHUN. It's fun!","CS_ID"=>25930,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"Hexayurt: Yurtin for Certain","CS_ID"=>25306,"Area"=>"West Green","New Subarea"=>"Grass A"),
  array("Exhibit"=>"Unnecessarily High Five","CS_ID"=>20038,"Area"=>"West Green","New Subarea"=>"Grass C"),
  array("Exhibit"=>"BioLite","CS_ID"=>32138,"Area"=>"West Green","New Subarea"=>"Grass C"),
  array("Exhibit"=>"The Being Booth","CS_ID"=>27306,"Area"=>"West Green","New Subarea"=>"Grass D"),
  array("Exhibit"=>"Cyber Spider","CS_ID"=>24401,"Area"=>"West Green","New Subarea"=>"Grass D"),
  array("Exhibit"=>"Ford ","CS_ID"=>32155,"Area"=>"West Green","New Subarea"=>"Grass D"),
  array("Exhibit"=>"Butterfly Frillies Corsets","CS_ID"=>19640,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"The future of festival fashion by Subverse Ind.","CS_ID"=>20676,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Rewind","CS_ID"=>23335,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Obtainium Works","CS_ID"=>23985,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"St. Clair Aeronauts Old Timey Letter Writing","CS_ID"=>21213,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Lighting the future by recycling the past","CS_ID"=>26314,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Wiredrawn Creations","CS_ID"=>19430,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Hats from the Retro-Apocalypse","CS_ID"=>19671,"Area"=>"West Green","New Subarea"=>"Grass F"),
  array("Exhibit"=>"Stamp and Seek","CS_ID"=>22904,"Area"=>"West Green","New Subarea"=>"Grass G"),
  array("Exhibit"=>"Tintype Photography from 1851","CS_ID"=>22738,"Area"=>"West Green","New Subarea"=>"Grass G"),
  array("Exhibit"=>"Imagination Technologies","CS_ID"=>32163,"Area"=>"West Green","New Subarea"=>"Grass G"),
  array("Exhibit"=>"Giant Cardboard Robots","CS_ID"=>26174,"Area"=>"West Green","New Subarea"=>"Grass H"),
  array("Exhibit"=>"Pokebots","CS_ID"=>25225,"Area"=>"West Green","New Subarea"=>"Grass H"),
  array("Exhibit"=>"OpenROV","CS_ID"=>21038,"Area"=>"West Green","New Subarea"=>"Grass I"),
  array("Exhibit"=>"Stanford Robotics Club","CS_ID"=>26816,"Area"=>"West Green","New Subarea"=>"Grass J"),
  array("Exhibit"=>"Oru Kayak","CS_ID"=>33171,"Area"=>"West Green","New Subarea"=>"Grass J"),
  array("Exhibit"=>"How to make your own Dobsonian Telescope","CS_ID"=>28181,"Area"=>"West Green","New Subarea"=>"Grass K"),
  array("Exhibit"=>"SketchUp ","CS_ID"=>32203,"Area"=>"West Green","New Subarea"=>"Grass K"),
  array("Exhibit"=>"streetbeats","CS_ID"=>26587,"Area"=>"West Green","New Subarea"=>"West"),
  array("Exhibit"=>"Giant Spirograph","CS_ID"=>23722,"Area"=>"West Green","New Subarea"=>""),
  array("Exhibit"=>"McPuzo & Trotsky","CS_ID"=>29724,"Area"=>"West Green","New Subarea"=>""),
  array("Exhibit"=>"Sadza Marimba","CS_ID"=>22214,"Area"=>"West Lot","New Subarea"=>"Coke Zero and Mentos Stage"),
  array("Exhibit"=>"Coke Zero & Mentos Fountains","CS_ID"=>29642,"Area"=>"West Lot","New Subarea"=>"Coke Zero and Mentos Stage"),
  array("Exhibit"=>"El Pulpo Mecanico","CS_ID"=>28408,"Area"=>"West Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"AVB.io","CS_ID"=>20827,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Metawear - Wearable Prototypes in 30 mins or less!","CS_ID"=>26661,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"RoboTar - Robotic chord hand for guitar","CS_ID"=>23639,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"BreadBoardManiac","CS_ID"=>24684,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Physicaloid : Physical computing for smartphone","CS_ID"=>23174,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Smart Phone Injector Keyboard","CS_ID"=>26580,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Plug-n-Blink. Because Bluetooth!","CS_ID"=>26093,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Voltset - Smart Digital Multimeter for Smartphones","CS_ID"=>23804,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"ISS-Above lights up when the ISS is ABOVE YOU!","CS_ID"=>23809,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"IOIO and PIXEL: LED ART","CS_ID"=>19943,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Gymtrack: A wearable device for fitness gaming.","CS_ID"=>23507,"Area"=>"West Lot","New Subarea"=>"Maker Pro"),
  array("Exhibit"=>"Life-Size Mousetrap","CS_ID"=>26604,"Area"=>"West Lot","New Subarea"=>"Mousetrap"),
  array("Exhibit"=>"EcoReco Corporation","CS_ID"=>32152,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Integreight","CS_ID"=>33156,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"BotFactory","CS_ID"=>32140,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"AgiC Inc","CS_ID"=>32130,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"AIO Robotics","CS_ID"=>32131,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Ufactory","CS_ID"=>32217,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Rise Robotics","CS_ID"=>32191,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Adam Beane Industries","CS_ID"=>32128,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Bare Conductive","CS_ID"=>32137,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Taktia","CS_ID"=>32210,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Hackaway","CS_ID"=>33153,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Shine On LED","CS_ID"=>32201,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Pinshape","CS_ID"=>32185,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Made Solid","CS_ID"=>32171,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"3D Monstr","CS_ID"=>33138,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Tinkerine","CS_ID"=>32214,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"QU-BD Inc.","CS_ID"=>32188,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Other Machine","CS_ID"=>32182,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Structure3D Printing","CS_ID"=>32205,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Carbide 3D","CS_ID"=>33144,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Sculpteo","CS_ID"=>32196,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Lightup Learning","CS_ID"=>32169,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Plotly","CS_ID"=>32186,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Concept Smarter Sketching","CS_ID"=>32148,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Proliner/Pontech","CS_ID"=>32187,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Makeblock","CS_ID"=>32172,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Code Bender","CS_ID"=>32144,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Carbon Origins","CS_ID"=>32142,"Area"=>"West Lot","New Subarea"=>"North"),
  array("Exhibit"=>"Battle Pond VII: Only the Bold Survive!","CS_ID"=>19877,"Area"=>"West Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"SubCommittee","CS_ID"=>20556,"Area"=>"West Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"Learn how to sail radio control boats","CS_ID"=>23936,"Area"=>"West Lot","New Subarea"=>"Northeast"),
  array("Exhibit"=>"The Turbinophone","CS_ID"=>26407,"Area"=>"West Lot","New Subarea"=>"Northwest"),
  array("Exhibit"=>"The Blown Ranger Rides Again","CS_ID"=>22813,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"CalSol, UC Berkeley Solar Vehicle Team","CS_ID"=>25589,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"EV Miata","CS_ID"=>20837,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Cheese Wedge, 1980 electric Comuta-Car","CS_ID"=>24475,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"RIP recycle in place all forms modern technology","CS_ID"=>22669,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"MG Locost","CS_ID"=>19989,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Switch Electric Vehicle","CS_ID"=>27760,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"EV for the Exited Driver","CS_ID"=>23426,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"MAX - A 100 MPG D-I-Y Sports Car","CS_ID"=>21980,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Electric Mega-Kart","CS_ID"=>26978,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Rusty Rocket Adult Soapbox Derby Car","CS_ID"=>27083,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"1994 Electric Truck by US Electricar.","CS_ID"=>21049,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Blackbird Super Cruiser Bicycle","CS_ID"=>20146,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Home built Neighborhood Electric Vehicle","CS_ID"=>31345,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Serpent Twins","CS_ID"=>29374,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Exploratorium","CS_ID"=>23409,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Five Ton Crane Arts Group","CS_ID"=>24171,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"The Nautilus Submarine","CS_ID"=>25077,"Area"=>"West Lot","New Subarea"=>"Southeast"),
  array("Exhibit"=>"Haxlr8r","CS_ID"=>32161,"Area"=>"West Lot","New Subarea"=>"Southwest")
);