<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "locations"
//

// locations.placement
$placement = array(
	array("CS_ID"=>11109,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11150,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11355,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11616,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11621,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11723,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11815,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>11926,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>12423,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>13371,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>13691,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14126,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14331,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14371,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14417,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14441,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14455,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>14488,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>15594,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>15784,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>16028,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>16038,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>16084,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>16778,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>17018,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>17192,"Area"=>"Zone A","New Subarea"=>"Innovation Stage","Location"=>""),
	array("CS_ID"=>10984,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>15665,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>17583,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10566,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10465,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10492,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10509,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10538,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10548,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10558,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10584,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10587,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10684,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10739,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10771,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10859,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10862,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10868,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>10871,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11040,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11086,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11118,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11170,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11322,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11337,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11420,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11435,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11456,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11484,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11546,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11567,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11578,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11645,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11651,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11668,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11703,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11705,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11721,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11738,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11782,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11898,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11908,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11942,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>11947,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12077,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12115,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12132,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12212,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12226,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12237,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12263,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12298,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12312,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12319,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12415,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12891,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>12923,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>13015,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>13051,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>13626,"Area"=>"Zone A","New Subarea"=>"Inside","Location"=>""),
	array("CS_ID"=>15601,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15620,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15627,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15632,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15640,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15648,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15675,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15680,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15891,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15898,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15904,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15937,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15944,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15950,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>15957,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>16652,"Area"=>"Zone A","New Subarea"=>"NYSCI Village","Location"=>""),
	array("CS_ID"=>11932,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>12163,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>13313,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>14574,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>14764,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>15379,"Area"=>"Zone A","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>10681,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10736,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10819,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10839,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10844,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10887,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11006,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11037,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11377,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11380,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11446,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11659,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11753,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>11914,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12079,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12085,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12100,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12154,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12161,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12373,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12409,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>12572,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>13706,"Area"=>"Zone A","New Subarea"=>"Viscusi Gallery","Location"=>""),
	array("CS_ID"=>10541,"Area"=>"Zone A","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>17594,"Area"=>"Zone B","New Subarea"=>"111th Street Roundabout","Location"=>"Place On Arrival"),
	array("CS_ID"=>12420,"Area"=>"Zone B","New Subarea"=>"111th Street Roundabout","Location"=>"RO01"),
	array("CS_ID"=>17415,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV01"),
	array("CS_ID"=>17440,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV02"),
	array("CS_ID"=>12195,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV04"),
	array("CS_ID"=>10949,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV05"),
	array("CS_ID"=>11402,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV06"),
	array("CS_ID"=>11686,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV07"),
	array("CS_ID"=>11479,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV08"),
	array("CS_ID"=>13293,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV09"),
	array("CS_ID"=>10895,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV10-11"),
	array("CS_ID"=>12111,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV12"),
	array("CS_ID"=>11541,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV13"),
	array("CS_ID"=>13017,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV14"),
	array("CS_ID"=>11494,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV15"),
	array("CS_ID"=>11532,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV16"),
	array("CS_ID"=>11369,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV17"),
	array("CS_ID"=>12019,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV18"),
	array("CS_ID"=>11363,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV19"),
	array("CS_ID"=>10525,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV20"),
	array("CS_ID"=>11407,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV21"),
	array("CS_ID"=>13844,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV22"),
	array("CS_ID"=>17423,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV24"),
	array("CS_ID"=>16912,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV25"),
	array("CS_ID"=>16906,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV26"),
	array("CS_ID"=>16916,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV27"),
	array("CS_ID"=>10853,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV28"),
	array("CS_ID"=>12872,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV29"),
	array("CS_ID"=>12098,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV30"),
	array("CS_ID"=>11716,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV31"),
	array("CS_ID"=>10882,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV32"),
	array("CS_ID"=>14035,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV33"),
	array("CS_ID"=>13334,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV34"),
	array("CS_ID"=>11175,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV35"),
	array("CS_ID"=>11297,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV36"),
	array("CS_ID"=>10794,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV37"),
	array("CS_ID"=>11848,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV38"),
	array("CS_ID"=>11881,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV39"),
	array("CS_ID"=>11538,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV40"),
	array("CS_ID"=>17507,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV41"),
	array("CS_ID"=>17473,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV42"),
	array("CS_ID"=>17419,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV44"),
	array("CS_ID"=>10879,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV45"),
	array("CS_ID"=>11803,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV46"),
	array("CS_ID"=>12965,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV47"),
	array("CS_ID"=>10768,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV48"),
	array("CS_ID"=>13286,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV49"),
	array("CS_ID"=>10829,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV50"),
	array("CS_ID"=>11253,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV51"),
	array("CS_ID"=>11218,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV52"),
	array("CS_ID"=>10759,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV53"),
	array("CS_ID"=>12145,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV54"),
	array("CS_ID"=>12234,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV55"),
	array("CS_ID"=>11410,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV56"),
	array("CS_ID"=>11075,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV57"),
	array("CS_ID"=>11235,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV58"),
	array("CS_ID"=>11137,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV59"),
	array("CS_ID"=>16695,"Area"=>"Zone B","New Subarea"=>"3D Printer Village","Location"=>"PV60"),
	array("CS_ID"=>11049,"Area"=>"Zone B","New Subarea"=>"Art Car","Location"=>"Place On Arrival"),
	array("CS_ID"=>13022,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS03"),
	array("CS_ID"=>10515,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS04"),
	array("CS_ID"=>12030,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS05"),
	array("CS_ID"=>12329,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS06"),
	array("CS_ID"=>12967,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS07"),
	array("CS_ID"=>12668,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS08"),
	array("CS_ID"=>12597,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS11"),
	array("CS_ID"=>11450,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS12"),
	array("CS_ID"=>11467,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS13"),
	array("CS_ID"=>10638,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS14"),
	array("CS_ID"=>10774,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS20"),
	array("CS_ID"=>10485,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS21"),
	array("CS_ID"=>11963,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS22"),
	array("CS_ID"=>10962,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS23A"),
	array("CS_ID"=>11032,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS23B"),
	array("CS_ID"=>11996,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS24"),
	array("CS_ID"=>12055,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS25A"),
	array("CS_ID"=>12007,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS25B"),
	array("CS_ID"=>10601,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS26"),
	array("CS_ID"=>10533,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS27A"),
	array("CS_ID"=>11186,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS27B"),
	array("CS_ID"=>12429,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS28"),
	array("CS_ID"=>11689,"Area"=>"Zone B","New Subarea"=>"Hackerspaces","Location"=>"HS30"),
	array("CS_ID"=>16964,"Area"=>"Zone B","New Subarea"=>"Make 3D","Location"=>"B01"),
	array("CS_ID"=>16897,"Area"=>"Zone B","New Subarea"=>"Make 3D","Location"=>"B02"),
	array("CS_ID"=>11238,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11257,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11662,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11806,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11874,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11944,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11955,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12041,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12119,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12135,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12201,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12203,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12217,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>12219,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>13298,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>13735,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>14045,"Area"=>"Zone B","New Subarea"=>"Make: 3D Printing Stage","Location"=>""),
	array("CS_ID"=>11780,"Area"=>"Zone B","New Subarea"=>"Maker Way","Location"=>"SP06"),
	array("CS_ID"=>10552,"Area"=>"Zone B","New Subarea"=>"Maker Way","Location"=>"ST01"),
	array("CS_ID"=>10959,"Area"=>"Zone B","New Subarea"=>"Maker Way","Location"=>"ST02"),
	array("CS_ID"=>10461,"Area"=>"Zone B","New Subarea"=>"Maker Way","Location"=>"ST04"),
	array("CS_ID"=>11785,"Area"=>"Zone B","New Subarea"=>"Maker Way","Location"=>"ST06"),
	array("CS_ID"=>16919,"Area"=>"Zone B","New Subarea"=>"Nerdy Derby","Location"=>"B50"),
	array("CS_ID"=>14159,"Area"=>"Zone B","New Subarea"=>"Nerdy Derby","Location"=>"ND50"),
	array("CS_ID"=>17586,"Area"=>"Zone B","New Subarea"=>"Nerdy Derby","Location"=>"Place On Arrival"),
	array("CS_ID"=>11776,"Area"=>"Zone B","New Subarea"=>"Ohm Wrestling","Location"=>"OB41"),
	array("CS_ID"=>12140,"Area"=>"Zone B","New Subarea"=>"Ohm Wrestling","Location"=>"OB42"),
	array("CS_ID"=>10597,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>11423,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>11426,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>11429,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>12581,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>13677,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>14284,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>14566,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>15354,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>15384,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>15808,"Area"=>"Zone B","New Subarea"=>"Power Racing Series Race Track","Location"=>"PR40"),
	array("CS_ID"=>11920,"Area"=>"Zone B","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>12089,"Area"=>"Zone B","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>12816,"Area"=>"Zone B","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>14060,"Area"=>"Zone B","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>14572,"Area"=>"Zone B","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>14412,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16365,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16366,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16367,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16368,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16371,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16372,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16373,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16374,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16375,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16376,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16377,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16378,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16380,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16381,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16382,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16383,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16384,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16385,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16386,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16387,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16388,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16389,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16390,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16391,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16392,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16393,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16394,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16395,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16396,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16397,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16398,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16399,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16400,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16401,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16402,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16403,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16404,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16405,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16406,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16407,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16408,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16409,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16410,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16411,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16412,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16413,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16414,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16415,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16416,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16417,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16418,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16419,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16420,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16421,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16422,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16423,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16424,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16425,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16426,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16427,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16428,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16429,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16430,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16431,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16432,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16435,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16439,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16443,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16447,"Area"=>"Zone C","New Subarea"=>"BUST Magazine Craftacular","Location"=>""),
	array("CS_ID"=>16921,"Area"=>"Zone C","New Subarea"=>"Center","Location"=>"Microsoft"),
	array("CS_ID"=>10750,"Area"=>"Zone C","New Subarea"=>"Center","Location"=>"Place On Arrival"),
	array("CS_ID"=>12725,"Area"=>"Zone C","New Subarea"=>"Center","Location"=>"Place On Arrival"),
	array("CS_ID"=>17482,"Area"=>"Zone C","New Subarea"=>"Center","Location"=>"Zazzle"),
	array("CS_ID"=>11923,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR05"),
	array("CS_ID"=>12222,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR06A"),
	array("CS_ID"=>12882,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR07"),
	array("CS_ID"=>13714,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR08"),
	array("CS_ID"=>12280,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR10"),
	array("CS_ID"=>10555,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR11"),
	array("CS_ID"=>12349,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR12"),
	array("CS_ID"=>12352,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR13"),
	array("CS_ID"=>12947,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR14"),
	array("CS_ID"=>12302,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR15"),
	array("CS_ID"=>11596,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR16"),
	array("CS_ID"=>10655,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR17"),
	array("CS_ID"=>12239,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"CR96A"),
	array("CS_ID"=>15278,"Area"=>"Zone C","New Subarea"=>"Craft","Location"=>"SW18"),
	array("CS_ID"=>11638,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP02"),
	array("CS_ID"=>13851,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP03"),
	array("CS_ID"=>10944,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP04A"),
	array("CS_ID"=>10954,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP04B"),
	array("CS_ID"=>16892,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP05"),
	array("CS_ID"=>16968,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP06"),
	array("CS_ID"=>16914,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP07"),
	array("CS_ID"=>12052,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP08"),
	array("CS_ID"=>12404,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP09"),
	array("CS_ID"=>12003,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP10"),
	array("CS_ID"=>12251,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP11A"),
	array("CS_ID"=>11978,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP11B"),
	array("CS_ID"=>12933,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP12"),
	array("CS_ID"=>11142,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP13"),
	array("CS_ID"=>11951,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP14A"),
	array("CS_ID"=>12205,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP14B"),
	array("CS_ID"=>12935,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP15"),
	array("CS_ID"=>13136,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP15"),
	array("CS_ID"=>11463,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP16"),
	array("CS_ID"=>13341,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP17"),
	array("CS_ID"=>10801,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP18"),
	array("CS_ID"=>12096,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP18"),
	array("CS_ID"=>12522,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP19"),
	array("CS_ID"=>16920,"Area"=>"Zone C","New Subarea"=>"Electronics Pavilion","Location"=>"EP21"),
	array("CS_ID"=>16984,"Area"=>"Zone C","New Subarea"=>"Learn to Solder","Location"=>"RadioShack"),
	array("CS_ID"=>17466,"Area"=>"Zone C","New Subarea"=>"Learn to Solder","Location"=>"RadioShack"),
	array("CS_ID"=>16833,"Area"=>"Zone C","New Subarea"=>"Make HQ","Location"=>""),
	array("CS_ID"=>10518,"Area"=>"Zone C","New Subarea"=>"Make HQ","Location"=>""),
	array("CS_ID"=>16704,"Area"=>"Zone C","New Subarea"=>"Make HQ","Location"=>""),
	array("CS_ID"=>17047,"Area"=>"Zone C","New Subarea"=>"Make HQ","Location"=>""),
	array("CS_ID"=>17093,"Area"=>"Zone C","New Subarea"=>"Make HQ","Location"=>""),
	array("CS_ID"=>16898,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"C40"),
	array("CS_ID"=>17451,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"C46"),
	array("CS_ID"=>10982,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA41"),
	array("CS_ID"=>12175,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA42"),
	array("CS_ID"=>12180,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA43"),
	array("CS_ID"=>11071,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA44"),
	array("CS_ID"=>11133,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA45"),
	array("CS_ID"=>11089,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA46"),
	array("CS_ID"=>11917,"Area"=>"Zone C","New Subarea"=>"Make Live Lane","Location"=>"SA50"),
	array("CS_ID"=>10604,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>10804,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>11207,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>11674,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>11829,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>11935,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>12260,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>12396,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>12853,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>13039,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>13062,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>13303,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>13716,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>14189,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>14197,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>14649,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>14661,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>16721,"Area"=>"Zone C","New Subarea"=>"Make: Education Café","Location"=>""),
	array("CS_ID"=>10447,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>10489,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>10593,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>11230,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>11248,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>11611,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>11788,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>11990,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12014,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12037,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12189,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12257,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12529,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>12915,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>14133,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>14202,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>15515,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>16177,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>16182,"Area"=>"Zone C","New Subarea"=>"Make: Electronics Stage","Location"=>""),
	array("CS_ID"=>10909,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>11274,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>11316,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>11439,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>11677,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>11735,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>12046,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>12062,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>12287,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>12476,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>12943,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>13008,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>13083,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>13096,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>13822,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>13834,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>14058,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>14108,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>14121,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>14728,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>15524,"Area"=>"Zone C","New Subarea"=>"Make: Live Stage","Location"=>""),
	array("CS_ID"=>16925,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP01"),
	array("CS_ID"=>12467,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP02"),
	array("CS_ID"=>11524,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP04"),
	array("CS_ID"=>11051,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP05"),
	array("CS_ID"=>12193,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP06"),
	array("CS_ID"=>12043,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP07A"),
	array("CS_ID"=>12553,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP07B"),
	array("CS_ID"=>17411,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP08"),
	array("CS_ID"=>17406,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP09"),
	array("CS_ID"=>16928,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP10"),
	array("CS_ID"=>16895,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP11"),
	array("CS_ID"=>16896,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP11"),
	array("CS_ID"=>12067,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP14"),
	array("CS_ID"=>16900,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP15"),
	array("CS_ID"=>11851,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP16A"),
	array("CS_ID"=>11570,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP16B"),
	array("CS_ID"=>16879,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP17"),
	array("CS_ID"=>16904,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP19"),
	array("CS_ID"=>17504,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP19"),
	array("CS_ID"=>16932,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP20"),
	array("CS_ID"=>16905,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP21"),
	array("CS_ID"=>16907,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP22"),
	array("CS_ID"=>16944,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP23"),
	array("CS_ID"=>17456,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP24"),
	array("CS_ID"=>16924,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP26"),
	array("CS_ID"=>17597,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP27"),
	array("CS_ID"=>16903,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP28"),
	array("CS_ID"=>16909,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP29"),
	array("CS_ID"=>16917,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP30"),
	array("CS_ID"=>17436,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP31"),
	array("CS_ID"=>16899,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP33"),
	array("CS_ID"=>16913,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP34"),
	array("CS_ID"=>17470,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP35"),
	array("CS_ID"=>16901,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP36"),
	array("CS_ID"=>16876,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP37"),
	array("CS_ID"=>17479,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP38"),
	array("CS_ID"=>16883,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP39"),
	array("CS_ID"=>16887,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP40"),
	array("CS_ID"=>16915,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP41"),
	array("CS_ID"=>16936,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP41"),
	array("CS_ID"=>17489,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP42"),
	array("CS_ID"=>17432,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP43"),
	array("CS_ID"=>16923,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP44"),
	array("CS_ID"=>16952,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP46"),
	array("CS_ID"=>17476,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP47"),
	array("CS_ID"=>17428,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP48"),
	array("CS_ID"=>17444,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP49"),
	array("CS_ID"=>11270,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP51"),
	array("CS_ID"=>16893,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP52"),
	array("CS_ID"=>16956,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP53"),
	array("CS_ID"=>16878,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP55"),
	array("CS_ID"=>12503,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP56"),
	array("CS_ID"=>16960,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP57"),
	array("CS_ID"=>11972,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP61"),
	array("CS_ID"=>16874,"Area"=>"Zone C","New Subarea"=>"Maker Pavilion","Location"=>"MP62"),
	array("CS_ID"=>11713,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS01"),
	array("CS_ID"=>11911,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS02"),
	array("CS_ID"=>10666,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>10988,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>11000,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>11200,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>11388,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>11820,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>11994,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>12137,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>12390,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>12790,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS03"),
	array("CS_ID"=>10480,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS06A"),
	array("CS_ID"=>11893,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS06B"),
	array("CS_ID"=>11500,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS07"),
	array("CS_ID"=>11431,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS08"),
	array("CS_ID"=>12268,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS08"),
	array("CS_ID"=>12336,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS08"),
	array("CS_ID"=>13755,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS08"),
	array("CS_ID"=>10659,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS10"),
	array("CS_ID"=>12017,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS10"),
	array("CS_ID"=>11100,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS11B"),
	array("CS_ID"=>10574,"Area"=>"Zone C","New Subarea"=>"Maker Square","Location"=>"MS12"),
	array("CS_ID"=>10832,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>10835,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>10912,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>10941,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11035,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11066,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11128,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11131,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11215,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11543,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11665,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11833,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11859,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>11902,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>12157,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>12559,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>12707,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>12980,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>14169,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>14289,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>14364,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>15411,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>16814,"Area"=>"Zone C","New Subarea"=>"Maker Square Stage","Location"=>""),
	array("CS_ID"=>12347,"Area"=>"Zone C","New Subarea"=>"Marshmallow Shooters","Location"=>"NE19"),
	array("CS_ID"=>11399,"Area"=>"Zone C","New Subarea"=>"Marshmallow Shooters","Location"=>"NE20"),
	array("CS_ID"=>11412,"Area"=>"Zone C","New Subarea"=>"Marshmallow Shooters","Location"=>"NE22"),
	array("CS_ID"=>12542,"Area"=>"Zone C","New Subarea"=>"North Corner","Location"=>"NC01"),
	array("CS_ID"=>11358,"Area"=>"Zone C","New Subarea"=>"North Corner","Location"=>"NC02"),
	array("CS_ID"=>11308,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR01"),
	array("CS_ID"=>16894,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR03"),
	array("CS_ID"=>13685,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR05"),
	array("CS_ID"=>11603,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR06"),
	array("CS_ID"=>11709,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR07"),
	array("CS_ID"=>11515,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR08"),
	array("CS_ID"=>16948,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR09"),
	array("CS_ID"=>10457,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR12"),
	array("CS_ID"=>11747,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR13"),
	array("CS_ID"=>11876,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR13"),
	array("CS_ID"=>12359,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR13"),
	array("CS_ID"=>14498,"Area"=>"Zone C","New Subarea"=>"Robot Row","Location"=>"RR13"),
	array("CS_ID"=>11751,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU01"),
	array("CS_ID"=>10798,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU02"),
	array("CS_ID"=>12450,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU03A"),
	array("CS_ID"=>10766,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU03B"),
	array("CS_ID"=>10762,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU04"),
	array("CS_ID"=>14597,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU04A"),
	array("CS_ID"=>14700,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU04B"),
	array("CS_ID"=>12171,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU05"),
	array("CS_ID"=>10885,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>"SU08"),
	array("CS_ID"=>12249,"Area"=>"Zone C","New Subarea"=>"Sustainability","Location"=>""),
	array("CS_ID"=>11155,"Area"=>"Zone C","New Subarea"=>"Swap-O-Rama-Rama","Location"=>"SW18"),
	array("CS_ID"=>16910,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM"),
	array("CS_ID"=>16911,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM"),
	array("CS_ID"=>12108,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM01A"),
	array("CS_ID"=>12143,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM01B"),
	array("CS_ID"=>11319,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM02"),
	array("CS_ID"=>11718,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM03"),
	array("CS_ID"=>11147,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM05"),
	array("CS_ID"=>17447,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM06"),
	array("CS_ID"=>11692,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM09"),
	array("CS_ID"=>11581,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM10"),
	array("CS_ID"=>13376,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM12"),
	array("CS_ID"=>11204,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM13"),
	array("CS_ID"=>13175,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM14A"),
	array("CS_ID"=>11836,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM14B"),
	array("CS_ID"=>11225,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM16"),
	array("CS_ID"=>12993,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM17A"),
	array("CS_ID"=>10590,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM17B"),
	array("CS_ID"=>12896,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM20"),
	array("CS_ID"=>12173,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM21A"),
	array("CS_ID"=>12275,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM21B"),
	array("CS_ID"=>10756,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM22A"),
	array("CS_ID"=>11352,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM22B"),
	array("CS_ID"=>12586,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM23"),
	array("CS_ID"=>11012,"Area"=>"Zone C","New Subarea"=>"Young Makers","Location"=>"YM24"),
	array("CS_ID"=>11764,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD12"),
	array("CS_ID"=>12903,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD20"),
	array("CS_ID"=>11301,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD21"),
	array("CS_ID"=>11106,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD22"),
	array("CS_ID"=>11697,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD23"),
	array("CS_ID"=>11366,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD25"),
	array("CS_ID"=>11871,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD26"),
	array("CS_ID"=>11091,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"CD28"),
	array("CS_ID"=>16940,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"D10"),
	array("CS_ID"=>16922,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"D12"),
	array("CS_ID"=>16918,"Area"=>"Zone D","New Subarea"=>"Central","Location"=>"D14"),
	array("CS_ID"=>15348,"Area"=>"Zone D","New Subarea"=>"Circus Warehouse","Location"=>"D15"),
	array("CS_ID"=>16040,"Area"=>"Zone D","New Subarea"=>"Coke Zero & Mentos Stage","Location"=>"Stage"),
	array("CS_ID"=>10690,"Area"=>"Zone D","New Subarea"=>"Coke Zero & Mentos Stage","Location"=>""),
	array("CS_ID"=>12121,"Area"=>"Zone D","New Subarea"=>"Farm Hack","Location"=>"BY31"),
	array("CS_ID"=>11335,"Area"=>"Zone D","New Subarea"=>"Fly Zone","Location"=>"FZ01"),
	array("CS_ID"=>12246,"Area"=>"Zone D","New Subarea"=>"Fly Zone","Location"=>"FZ01"),
	array("CS_ID"=>13047,"Area"=>"Zone D","New Subarea"=>"Fly Zone","Location"=>"FZ03"),
	array("CS_ID"=>14309,"Area"=>"Zone D","New Subarea"=>"Fly Zone","Location"=>"FZ2"),
	array("CS_ID"=>16050,"Area"=>"Zone D","New Subarea"=>"Life-Size Mousetrap","Location"=>"D13"),
	array("CS_ID"=>10645,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>12465,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>12848,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>13200,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>13617,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>14267,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>15527,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>15567,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>15573,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>16011,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>16266,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>16344,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>16575,"Area"=>"Zone D","New Subarea"=>"Maker Shed","Location"=>""),
	array("CS_ID"=>11680,"Area"=>"Zone D","New Subarea"=>"Makey","Location"=>"Place On Arrival"),
	array("CS_ID"=>11731,"Area"=>"Zone D","New Subarea"=>"Quad Zone","Location"=>"NE03"),
	array("CS_ID"=>12049,"Area"=>"Zone D","New Subarea"=>"Quad Zone","Location"=>"NE08"),
	array("CS_ID"=>10865,"Area"=>"Zone D","New Subarea"=>"Quad Zone","Location"=>"NE09"),
	array("CS_ID"=>11329,"Area"=>"Zone D","New Subarea"=>"Rocket Roundabout","Location"=>"RO71"),
	array("CS_ID"=>17486,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"D63"),
	array("CS_ID"=>12198,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA51"),
	array("CS_ID"=>10904,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA52"),
	array("CS_ID"=>12294,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA53"),
	array("CS_ID"=>11575,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA54"),
	array("CS_ID"=>13809,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA55"),
	array("CS_ID"=>14030,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA56"),
	array("CS_ID"=>11599,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA60"),
	array("CS_ID"=>11182,"Area"=>"Zone D","New Subarea"=>"Science Avenue","Location"=>"SA65"),
	array("CS_ID"=>12278,"Area"=>"Zone D","New Subarea"=>"South","Location"=>"BY30"),
	array("CS_ID"=>15599,"Area"=>"Zone D","New Subarea"=>"South","Location"=>""),
	array("CS_ID"=>15603,"Area"=>"Zone D","New Subarea"=>"South","Location"=>""),
	array("CS_ID"=>10535,"Area"=>"Zone D","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>11801,"Area"=>"Zone D","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>11059,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E01"),
	array("CS_ID"=>11584,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E02"),
	array("CS_ID"=>12565,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E03"),
	array("CS_ID"=>11113,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E04"),
	array("CS_ID"=>16908,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E07"),
	array("CS_ID"=>17577,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E08"),
	array("CS_ID"=>17566,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E09"),
	array("CS_ID"=>11003,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E15"),
	array("CS_ID"=>10846,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E17"),
	array("CS_ID"=>12316,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E18"),
	array("CS_ID"=>11373,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E19"),
	array("CS_ID"=>12152,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E20"),
	array("CS_ID"=>12321,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E21"),
	array("CS_ID"=>11294,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E22"),
	array("CS_ID"=>12009,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E31"),
	array("CS_ID"=>10669,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E32"),
	array("CS_ID"=>14135,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E33"),
	array("CS_ID"=>11590,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E34"),
	array("CS_ID"=>10687,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E37"),
	array("CS_ID"=>13104,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E38"),
	array("CS_ID"=>13026,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E39"),
	array("CS_ID"=>10826,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E40"),
	array("CS_ID"=>12511,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E41"),
	array("CS_ID"=>11854,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E49"),
	array("CS_ID"=>11313,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E53"),
	array("CS_ID"=>12000,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E55"),
	array("CS_ID"=>12117,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E56"),
	array("CS_ID"=>11347,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E57"),
	array("CS_ID"=>12072,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E58"),
	array("CS_ID"=>11863,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E59"),
	array("CS_ID"=>10693,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E60"),
	array("CS_ID"=>12104,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E63"),
	array("CS_ID"=>10952,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E64"),
	array("CS_ID"=>11792,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E65"),
	array("CS_ID"=>12366,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"E66"),
	array("CS_ID"=>17580,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"Place On Arrival"),
	array("CS_ID"=>11867,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"Place On Arrival"),
	array("CS_ID"=>11121,"Area"=>"Zone E","New Subarea"=>"Family Fun","Location"=>"Place On Arrival"),
	array("CS_ID"=>12436,"Area"=>"Zone E","New Subarea"=>"Roaming","Location"=>"Mobile"),
	array("CS_ID"=>16926,"Area"=>"","New Subarea"=>"","Location"=>"N/A"),
	array("CS_ID"=>17590,"Area"=>"","New Subarea"=>"","Location"=>"Place On Arrival"),
	array("CS_ID"=>10707,"Area"=>"","New Subarea"=>"","Location"=>"Presenter"),
	array("CS_ID"=>10672,"Area"=>"","New Subarea"=>"","Location"=>"TEST"),
	array("CS_ID"=>10561,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>10742,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>11325,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>11987,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>12270,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>12384,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>12418,"Area"=>"","New Subarea"=>"","Location"=>""),
	array("CS_ID"=>16062,"Area"=>"","New Subarea"=>"","Location"=>"")
);