<?php
//
// Database "locations"
//

// locations.placement
$placement = array(
	// Local testing here:
	// array("ID"=>5852,"Area"=>"Expo Hall","Subarea"=>"Expo West")

	// Here we go!
	array("ID"=>22234,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>22862,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>23617,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>26787,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>28061,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>28482,"Area"=>"East Side","Subarea"=>"Mobile"),
	array("ID"=>19610,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>22218,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>22462,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>23066,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>23921,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>24099,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>24819,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>25452,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>25457,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>25876,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>26384,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>26606,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>26734,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>26893,"Area"=>"Expo","Subarea"=>"East"),
	array("ID"=>20355,"Area"=>"Expo","Subarea"=>"Mobile"),
	array("ID"=>25208,"Area"=>"Expo","Subarea"=>"Mobile"),
	array("ID"=>27087,"Area"=>"Expo","Subarea"=>"Mobile"),
	array("ID"=>20094,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>20390,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>22229,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>22266,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>22290,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>22736,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>22877,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>23615,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>23652,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>23909,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>24631,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>24779,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>24989,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>25058,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>25238,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>25287,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>26048,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>26492,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>27136,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>27376,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>28349,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>30521,"Area"=>"Expo","Subarea"=>"Northeast"),
	array("ID"=>19632,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>19953,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20194,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20436,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20458,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20547,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20636,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>20725,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>21044,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>21339,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>21603,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>21765,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>22445,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>22699,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>23207,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>23671,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24076,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24386,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24465,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24575,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24586,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>24959,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>25403,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>25543,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>26100,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>26438,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>26477,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>26490,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>26622,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>27031,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>27262,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>28103,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>28271,"Area"=>"Expo","Subarea"=>"Northwest"),
	array("ID"=>22537,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>28303,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>28310,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>28665,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>28765,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29127,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29224,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29269,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29451,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29476,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29560,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29603,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29882,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29907,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>29937,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>30021,"Area"=>"Expo","Subarea"=>"South"),
	array("ID"=>19351,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>19517,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>19719,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>19754,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>19869,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>20184,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>20340,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>20620,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>20742,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>20818,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21168,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21174,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21229,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21280,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21296,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21315,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21329,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21335,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21500,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>21947,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22337,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22458,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22508,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22593,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22721,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>22964,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23154,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23253,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23339,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23503,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23826,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>23928,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24176,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24594,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24627,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24629,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24657,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24675,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24680,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24746,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24838,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24916,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>24982,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>25023,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>25034,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>25345,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>25443,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>25614,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>26795,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>26842,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>27105,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>27153,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>28092,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>28739,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>29502,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>30401,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>30426,"Area"=>"Expo","Subarea"=>"Southeast"),
	array("ID"=>19691,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>19804,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>19995,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>20214,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>20699,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>20870,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>20952,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>21310,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>21673,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22030,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22157,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22205,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22325,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22464,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22485,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>22530,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23022,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23070,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23231,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23490,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23662,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23843,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23863,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>23941,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24088,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24180,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24217,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24286,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24310,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>24344,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25027,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25065,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25079,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25148,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25158,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25186,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25301,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25598,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25601,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>25662,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>26633,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>26746,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>26862,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>27095,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>28429,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>28472,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>30871,"Area"=>"Expo","Subarea"=>"Southwest"),
	array("ID"=>19466,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>19543,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>19983,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>20280,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>20309,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>20338,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>20377,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>20801,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>21187,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>22682,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>22982,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>23324,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>23383,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>23565,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>23752,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>23852,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24012,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24342,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24384,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24774,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24792,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>24975,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25025,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25134,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25248,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25250,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25341,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25517,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>27024,"Area"=>"Expo","Subarea"=>"West"),
	array("ID"=>25388,"Area"=>"Expo","Subarea"=>""),
	array("ID"=>20948,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>21130,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>22999,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>23555,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>25323,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>27282,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>28797,"Area"=>"Fiesta","Subarea"=>"Center"),
	array("ID"=>20380,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>21527,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>22714,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>24038,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>25075,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>27468,"Area"=>"Fiesta","Subarea"=>"Foyer East"),
	array("ID"=>19859,"Area"=>"Fiesta","Subarea"=>"Foyer West"),
	array("ID"=>23060,"Area"=>"Fiesta","Subarea"=>"Foyer West"),
	array("ID"=>24512,"Area"=>"Fiesta","Subarea"=>"Mobile"),
	array("ID"=>25470,"Area"=>"Fiesta","Subarea"=>"Mobile"),
	array("ID"=>25538,"Area"=>"Fiesta","Subarea"=>"Mobile"),
	array("ID"=>21790,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>22406,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>23371,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>23573,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>23777,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>24569,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>25051,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>25062,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>25489,"Area"=>"Fiesta","Subarea"=>"Northeast"),
	array("ID"=>20003,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>20647,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>20669,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>21158,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>22368,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>24596,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>24848,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>24896,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>26404,"Area"=>"Fiesta","Subarea"=>"Northwest"),
	array("ID"=>21639,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>22555,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>22596,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>22634,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>22931,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>25831,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>26756,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>26812,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>27171,"Area"=>"Fiesta","Subarea"=>"Southeast"),
	array("ID"=>21179,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>21349,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>22898,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>23898,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>25429,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>26348,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>26987,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>27301,"Area"=>"Fiesta","Subarea"=>"Southwest"),
	array("ID"=>19321,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>19562,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>21514,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>25263,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>25477,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>25526,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>26350,"Area"=>"Fiesta","Subarea"=>"Wing A"),
	array("ID"=>21009,"Area"=>"Meeting Pavilion","Subarea"=>"Center Stage"),
	array("ID"=>19678,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>19836,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>24957,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>25564,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>25869,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>27749,"Area"=>"Midway","Subarea"=>"Center"),
	array("ID"=>20950,"Area"=>"North Courtyard","Subarea"=>"Center"),
	array("ID"=>23180,"Area"=>"North Courtyard","Subarea"=>"Center"),
	array("ID"=>23533,"Area"=>"North Courtyard","Subarea"=>"Center"),
	array("ID"=>25562,"Area"=>"North Courtyard","Subarea"=>"Center"),
	array("ID"=>27511,"Area"=>"North Courtyard","Subarea"=>"Center"),
	array("ID"=>20081,"Area"=>"North Courtyard","Subarea"=>"South"),
	array("ID"=>24663,"Area"=>"North Courtyard","Subarea"=>"South"),
	array("ID"=>25252,"Area"=>"North Courtyard","Subarea"=>"South"),
	array("ID"=>26042,"Area"=>"North Courtyard","Subarea"=>"South"),
	array("ID"=>26907,"Area"=>"North Courtyard","Subarea"=>"South"),
	array("ID"=>26121,"Area"=>"North Courtyard","Subarea"=>"Southeast"),
	array("ID"=>21123,"Area"=>"North Courtyard","Subarea"=>"Southwest"),
	array("ID"=>23132,"Area"=>"Redwood","Subarea"=>"Maker Shed"),
	array("ID"=>25399,"Area"=>"Redwood","Subarea"=>"Maker Shed"),
	array("ID"=>28677,"Area"=>"Redwood","Subarea"=>"Maker Shed"),
	array("ID"=>30352,"Area"=>"Redwood","Subarea"=>"Maker Shed"),
	array("ID"=>30376,"Area"=>"Redwood","Subarea"=>"Maker Shed"),
	array("ID"=>23814,"Area"=>"Redwood","Subarea"=>"Outside North"),
	array("ID"=>19919,"Area"=>"Redwood","Subarea"=>"Outside Northwest"),
	array("ID"=>19977,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>20069,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>20659,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>20978,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21270,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21302,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21414,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21416,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21434,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21437,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21439,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21441,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21447,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21459,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21664,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>21691,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>22541,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>22647,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>22879,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23095,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23098,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23309,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23524,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23563,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23631,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>23696,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>25175,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>25317,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>28215,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>28508,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>28514,"Area"=>"Sequoia","Subarea"=>"Young Makers"),
	array("ID"=>22650,"Area"=>"South Lot","Subarea"=>"Mobile"),
	array("ID"=>25111,"Area"=>"South Lot","Subarea"=>"Mobile"),
	array("ID"=>26196,"Area"=>"South Lot","Subarea"=>"Mobile"),
	array("ID"=>27531,"Area"=>"South Lot","Subarea"=>"Mobile"),
	array("ID"=>19454,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20298,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20529,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20788,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20864,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20987,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>21000,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>21363,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>22591,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>22934,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>23456,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>23787,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>24158,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>24332,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>24784,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>24825,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>25757,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>26328,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>26613,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>27008,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>27141,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>28324,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>29697,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>30778,"Area"=>"South Lot","Subarea"=>"Northeast"),
	array("ID"=>20331,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>20638,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>20778,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>20794,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>22278,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>22439,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>22757,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>22948,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>23056,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>23178,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>25010,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>25315,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>26190,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>26271,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>28506,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>28652,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>28971,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29008,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29472,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29482,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29713,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29718,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29823,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>29891,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>30809,"Area"=>"South Lot","Subarea"=>"Northwest"),
	array("ID"=>19821,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>19937,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>21020,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>21116,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>21191,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>23012,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>23152,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>23964,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>24494,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>25004,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>26591,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>26900,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>27365,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>27561,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>28338,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>29864,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>null,"Area"=>"South Lot","Subarea"=>"Southeast"),
	array("ID"=>20464,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>21635,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>22164,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>23186,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>24094,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>24252,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>25417,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>26889,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>28206,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>28240,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>29364,"Area"=>"South Lot","Subarea"=>"Southwest"),
	array("ID"=>19763,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>20396,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>20767,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>20858,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>21146,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>21524,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>22180,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>22580,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>23500,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>23736,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24184,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24206,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24299,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24346,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24437,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24695,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>24801,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>25431,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>25435,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>25487,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>25556,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>26277,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>26428,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>26496,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>26578,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>26761,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>27553,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>27789,"Area"=>"The Yard","Subarea"=>"North"),
	array("ID"=>21218,"Area"=>"The Yard","Subarea"=>"South"),
	array("ID"=>25231,"Area"=>"The Yard","Subarea"=>"South"),
	array("ID"=>23704,"Area"=>"West Green","Subarea"=>"Center E"),
	array("ID"=>23007,"Area"=>"West Green","Subarea"=>"Expo West"),
	array("ID"=>24644,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>24878,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>25306,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>25437,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>25905,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>25930,"Area"=>"West Green","Subarea"=>"Grass A"),
	array("ID"=>20038,"Area"=>"West Green","Subarea"=>"Grass C"),
	array("ID"=>24401,"Area"=>"West Green","Subarea"=>"Grass D"),
	array("ID"=>27306,"Area"=>"West Green","Subarea"=>"Grass D"),
	array("ID"=>19430,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>19640,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>19671,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>20676,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>21213,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>23335,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>23985,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>26314,"Area"=>"West Green","Subarea"=>"Grass F"),
	array("ID"=>22738,"Area"=>"West Green","Subarea"=>"Grass G"),
	array("ID"=>22904,"Area"=>"West Green","Subarea"=>"Grass G"),
	array("ID"=>26174,"Area"=>"West Green","Subarea"=>"Grass H"),
	array("ID"=>21038,"Area"=>"West Green","Subarea"=>"Grass I"),
	array("ID"=>26816,"Area"=>"West Green","Subarea"=>"Grass J"),
	array("ID"=>28181,"Area"=>"West Green","Subarea"=>"Grass K"),
	array("ID"=>26587,"Area"=>"West Green","Subarea"=>"West"),
	array("ID"=>23722,"Area"=>"West Green","Subarea"=>""),
	array("ID"=>19877,"Area"=>"West Lot","Subarea"=>"Northeast"),
	array("ID"=>20556,"Area"=>"West Lot","Subarea"=>"Northeast"),
	array("ID"=>23936,"Area"=>"West Lot","Subarea"=>"Northeast"),
	array("ID"=>26407,"Area"=>"West Lot","Subarea"=>"Northwest"),
	array("ID"=>28408,"Area"=>"West Lot","Subarea"=>"Northwest"),
	array("ID"=>19989,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>20146,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>20837,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>21049,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>21980,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>22669,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>22813,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>23409,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>24171,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>24475,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>25077,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>25589,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>26604,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>26978,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>27083,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>27760,"Area"=>"West Lot","Subarea"=>"Southeast"),
	array("ID"=>29374,"Area"=>"West Lot","Subarea"=>"Southeast"),
);